"""A framework for solving reasoning tasks using Tree of Thoughts.

Nodes within the tree represent partial progress towards solving a reasoning task.
Edges represent the reasoning steps that are possible to take from one node to another
(e.g., reflecting on previous steps, introducing examples, considering opposing views, etc...).

We leverage the BFS (Beam Search) algorithm proposed in Tree of Thoughts (Yao et al., 2023)
to solve complex reasoning tasks.

In our framework, users define a task through a generator (DSPy) signature, and a means to evaluate
that task through the evaluator (DSPy) signature.

The generator produces reasoning steps (or final responses) given the input and prior reasoning
steps (if any). The generator can be controlled by a controller, which generates prefixes
(interventions) to guide the generation of the next reasoning step.
The evaluator assigns quality scores to generated reasoning steps or responses based on
task-specific criteria.

In order to prevent the tree from growing exponentially, we select the top-k nodes to expand at
each layer of the tree (and prune the rest) at each step of the tree search.
This allows us to focus on the most promising reasoning chains and avoid exploring less promising
reasoning paths.

Key Components:
    - **Generator**: Produces reasoning steps (or final responses) given input and prior reasoning
		steps (if any). The generator can be controlled by a controller, which generates prefixes
		(interventions) to guide the generation of the next reasoning step.
    - **Evaluator**: Assigns quality scores to generated reasoning steps or responses based on
		task-specific criteria.
    - **Controller**: A controller that generates prefixes (interventions) to guide the generation
		of the next reasoning step. The controller can be used to early-stop the tree search or to
		use tools that translate to interventions.
    - **Tree**: Represents reasoning steps and final responses as nodes in a tree.
		Nodes are connected by edges, where root-to-leaf paths represent reasoning chains for
		solving the task.

Basic Notation:
    - `x`: Input problem or task description. In our case, `x` entails the input fields for the
		task (defined by the generator signature)
    - `y`: Final response or prediction. In our case, `y` is the output fields for the task
		(defined by the generator signature)
	- `z`: Intermediate reasoning step. These are partial responses or thoughts that help generate
		the final response, `y`. A sequence of reasoning steps from `x` to `y` is denoted as `Z`.
    - `m`: Number of samples to generate for each reasoning step (i.e., number of child nodes for
		each parent node in the tree) for each node in the frontier at each step of the tree search
    - `n`: Number of reasoning steps to take in the tree (not including the final response)
    - `k`: Number of top-scoring candidates to select for further expansion in the tree
    - `l`: Number of candidate versions for final response or prediction `y` to generate at each
		step of the tree search, where `l <= k`.
    - `v(x, y)`: Evaluation function (PRM) that assigns a quality score to a final response.
    - `v(x, Z_i)`: Evaluation function (PRM) that assigns a quality score to a chain of reasoning
		steps `Z_i := [z_1, ..., z_i]` given input `x`.
    - `v(x, Z, y)`: Evaluation function (ORM) that assigns a quality score to a chain of reasoning
		steps `Z := [z_1, ..., z_i]` given input `x` and a final response `y`.
    - `z_1`: First reasoning step.
    - `z_i`: i-th reasoning step generated by the i-th node (where 1 <= i <= n).
    - `z_(1, j)`: The j'th candidate for the first reasoning step (where 1 <= j <= m).
    - `z_(i, j)`: The j'th candidate for the i'th reasoning step (where 0 <= j < m and 0 <= i < n).
    - `y_(j)`: The j'th candidate for the final response (where 1 <= j <= m).
		A final response is derived from a sequence of reasoning steps (`z_1, ..., z_n`).

Framework Workflow:
    1. **Initialization**: A root node is created for the input problem (`x`).
	2. **Planning**: Call the Controller to guide generation for each node in the current layer
	(optional).
    3. **Generation**: Generate `m` new reasoning steps, `z_(i, 1), ..., z_(i, m)`, for each node
	in the current layer.
    4. **Evaluation**: Evaluate the quality of each new reasoning chain, `x, z_1, ..., z_i`,
		using task-specific criteria, `v(x, Z)`. If the trajectory includes a final response,
		also evaluate the quality of the final response, `y`, using task-specific criteria,
		`v(x, Z, y)`.
    5. **Selection**: Top-k nodes (and their corresponding chains) are selected for expansion
		in the next layer.
    6. **Iteration**: Steps 2-5 are repeated until the desired tree depth is reached.
    7. **Finalization**: The best `l` reasoning chain(s) are identified, and the corresponding
		final response(s) (if any) are returned.
"""

# Standard library imports
import logging
import random
import time
from collections import defaultdict
from collections.abc import Callable
from dataclasses import asdict
from pathlib import Path
from typing import Any, Literal

# Third-party imports
import dspy
import numpy as np
import torch
from pydantic import BaseModel, Field
from tqdm import tqdm

# Local imports
from adapter.adapter_constants import FINAL_OUTPUT_KIND_TYPE
from adapter.constraints import ResponseLength
from constants import VERBOSITY_TO_LOGGING_LEVEL, Verbosity
from lm.generative_local_lm import GenerativeLocalVLLM
from lm.scoring_local_lm import ScoringLocalVLLM
from misc_utils import (
	ExecutionError,
	format_generated_node_log,
	stringify,
)
from predict.controller.controller import TreeOfThoughtsController
from predict.controller.controller_constants import ControllerOutput
from predict.controller.controller_reranker import TreeOfThoughtsControllerReranker
from predict.controller.controller_utils import (
	return_action_if_single_option,
)
from predict.evaluator.evaluator import TreeOfThoughtEvaluator
from predict.evaluator.evaluator_programmatic import (
	ProgrammaticEvaluationInput,
	TreeOfThoughtProgrammaticEvaluator,
)
from predict.evaluator.evaluator_reranker import TreeOfThoughtRerankerEvaluator
from predict.generator.generator import TreeOfThoughtGenerator
from predict.tree_of_thoughts.tree_of_thoughts_utils import (
	format_controller_output,
	format_step_info,
)
from predict.tree_of_thoughts.tree_parameters import (
	NodeSelectionStrategy,
	TreeOfThoughtsParameters,
)
from signatures import ReasoningSignature
from signatures.signature import ensure_reasoning_signature
from tree import (
	Input,
	Node,
	ReasoningChain,
	State,
	Tree,
)
from tree.tree_constants import (
	NodeField,
	ToTField,
)

# Set up logging
if not logging.getLogger().handlers:
	logging.basicConfig(
		level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
	)
logger = logging.getLogger(__name__)


class Response(BaseModel):
	"""A final response generated by the Tree-Of-Thoughts program.

	The response is a dictionary mapping output field names (from the generator signature)
	to their values. The structure depends on the generator signature's output fields.
	"""

	response_data: dict[str, Any] = Field(
		...,
		description="Dictionary containing response data with output field names as keys.",
	)

	@classmethod
	def from_dict(cls, data: dict[str, Any]) -> "Response":
		"""Create a Response from a dictionary."""
		return cls(response_data=data)

	def to_dict(self) -> dict[str, Any]:
		"""Convert Response back to dictionary."""
		return self.response_data


class TreeOfThoughtsOutput(BaseModel):
	"""
	A prediction generated by the Tree-Of-Thoughts program.

	The prediction includes a collection of candidate final responses, the reasoning chains that
	led to these responses, the reasoning tree from which the responses were derived, the cost of
	running the tree of thoughts, and the runtime of the tree of thoughts.
	"""

	responses: list[Response] = Field(
		..., description="A collection of final responses.", alias=ToTField.RESPONSES
	)
	reasoning_steps: list[ReasoningChain] = Field(
		...,
		description="A collection of reasoning chains that led to the answer.",
		alias=ToTField.REASONING_STEPS,
	)
	response_strings: list[str] = Field(
		...,
		description="A collection of final responses formatted as strings.",
		alias=ToTField.RESPONSE_STRINGS,
	)
	tree: Tree = Field(
		...,
		description="The reasoning tree from which the final responses were derived.",
		alias=ToTField.TREE,
	)
	# TODO[P3]: Add support for cost calculation if using API calls to open-source models
	# as opposed to hosting them locally.
	cost: float | None = Field(
		default=None,
		description="The cost of running the tree of thoughts (in USD).",
		alias=ToTField.COST,
	)
	runtime: float = Field(
		...,
		description="The runtime of the tree of thoughts (in seconds).",
		alias=ToTField.RUNTIME,
	)


def build_tree_log_payload(
	tree: Tree,
	tot_parameters: TreeOfThoughtsParameters,
	tot_output: TreeOfThoughtsOutput,
) -> dict[str, Any]:
	"""Create a JSON-serializable payload capturing the full Tree of Thoughts run."""
	tree_payload = tree.tree_to_json()
	output_payload = []
	for index, (response, chain) in enumerate(
		zip(tot_output.responses, tot_output.reasoning_steps, strict=True)
	):
		output_payload.append(
			{
				"response": response.to_dict(),
				"response_string": tot_output.response_strings[index],
				"reasoning_chain": [node.model_dump() for node in chain.nodes],
			}
		)
	return {
		"tree_of_thoughts_parameters": asdict(tot_parameters),
		"tree_outputs": output_payload,
		"tree_metadata": {
			"runtime_seconds": tot_output.runtime,
			"cost": tot_output.cost,
		},
		"tree": tree_payload,
	}


def log_tree_run(
	tree: Tree,
	tot_parameters: TreeOfThoughtsParameters,
	tot_output: TreeOfThoughtsOutput,
	directory_path: str | None = None,
	file_name: str | None = None,
) -> dict[str, Any]:
	"""
	Serialize and persist a Tree of Thoughts run.

	Parameters:
	    tree: Tree structure to serialize.
	    tot_parameters: Parameters used for the run.
	    tot_output: Final outputs and reasoning chains.
	    directory_path: Optional directory for the log.
	    file_name: Optional filename for the log. If provided and include_date_time
			is True, a timestamp will be appended before the file extension.

	Returns:
	    Dict containing the serialized run.
	"""
	payload = build_tree_log_payload(
		tree=tree,
		tot_parameters=tot_parameters,
		tot_output=tot_output,
	)
	# Determine the actual filename that will be saved (with timestamp if applicable)
	actual_file_name = file_name
	if file_name is not None:
		timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
		if file_name.endswith(".json"):
			actual_file_name = f"{file_name[:-5]}_{timestamp}.json"
		else:
			actual_file_name = f"{file_name}_{timestamp}.json"
	elif file_name is None:
		actual_file_name = f"additive_reasoning_tree_{time.strftime('%Y-%m-%d_%H-%M-%S')}.json"

	Tree.save_json_to_file(
		tree_json=payload,
		directory_path=directory_path,
		file_name=file_name,
		include_date_time=True,
	)
	logger.info(f"Saved tree to {directory_path}/{actual_file_name}")
	return payload


class TreeOfThoughts(dspy.Module):
	"""Utilizes Tree-of-Thoughts to answer complex reasoning tasks.

	In our notation, given some input problem, `x`, the model is tasked with producing thoughts,
	`Z := [z_1, ..., z_n]` in order to generate a high-quality final response, `y`, for the task.

	Each `z` is a reasoning step towards `y`, where `z_i` denotes the `i`-th reasoning step in a
	reasoning chain `Z`.
	The final response, `y`, is derived from both the input, `x`, and the intermediate reasoning
	steps, `z_1, ..., z_n` (where `n` is the pre-defined number of reasoning steps to take).

	Each new intermediate reasoning step (`z`) should help (or increase the likelihood of)
	producing a high-quality final response, `y`, for the task.

	The generator creates `m` candidates for each reasoning step:
	`Z_i := [z_(i, 1), z_(i, 2), ..., z_(i, m)]`, where `m` is the number of samples to generate.
	Each of these `m` candidates is evaluated, and only the `top_k` highest-scoring candidates
	are explored further. The value for `m` is controlled by the `n_samples_generation` parameter.

	Once we have `m` candidates for each reasoning step, we evaluate them using the evaluator.
	The evaluator assigns a quality score to each candidate based on task-specific criteria.
	The top-k candidates are then selected for further expansion in the tree.
	The value for `k` is controlled by the `top_k` parameter.

	The process continues for `n` reasoning steps, where `n` is the depth of the tree.
	The final `1 <= l <= k` final response(s), `y`, are derived from the highest-scoring reasoning
	chain(s) (if any).
	"""

	def _set_lm(
		self,
		generative_lm: GenerativeLocalVLLM | None,
		reranker_lm: ScoringLocalVLLM | None = None,
	) -> GenerativeLocalVLLM:
		"""
		Set the language model for the Tree-Of-Thoughts module.

		Sets the LM for generator, evaluator, and controller.

		Parameters:
			generative_lm (GenerativeLocalVLLM | None): The language model to use for the generator,
				evaluator, and controller (if controller_type is GENERATOR). Falls back to
				dspy.settings.lm if None.
			reranker_lm (ScoringLocalVLLM | None): The language model to use for the reranker
				controller.

		Returns:
			The generative language model instance.

		Raises:
			AssertionError: If the language model is not a GenerativeLocalVLLM instance or is None.
			ValueError: If using a reranker controller and the reranker language model is not provided.
			ValueError: If an invalid controller type is provided.
		"""
		generative_lm = generative_lm if generative_lm is not None else dspy.settings.lm
		assert generative_lm is not None, "generative_lm must not be None"
		assert isinstance(generative_lm, GenerativeLocalVLLM), (
			"generative_lm must be a GenerativeLocalVLLM instance"
		)
		self.generator.lm = generative_lm
		if self.evaluator_type == "generator":
			self.evaluator.process_evaluator.set_lm(generative_lm)
			self.evaluator.outcome_evaluator.set_lm(generative_lm)
		elif self.evaluator_type == "programmatic":
			pass
		else:
			if reranker_lm is None or not isinstance(reranker_lm, ScoringLocalVLLM):
				raise ValueError(
					"reranker_lm must be provided when evaluator_type is RERANKER. "
					"Please initialize a ScoringLocalVLLM and pass it as reranker_lm.\n"
					f"Got {reranker_lm} of type {type(reranker_lm)}."
				)
			self.evaluator.set_lm(reranker_lm)
		# Set controller LM for both generator and reranker controllers
		if self.controller_type == "generator":
			self.controller.set_lm(generative_lm)
		elif self.controller_type == "reranker":
			if reranker_lm is None or not isinstance(reranker_lm, ScoringLocalVLLM):
				raise ValueError(
					"reranker_lm must be provided when controller_type is RERANKER. "
					"Please initialize a ScoringLocalVLLM and pass it as reranker_lm.\n"
					f"Got {reranker_lm} of type {type(reranker_lm)}."
				)
			self.controller.set_lm(reranker_lm)
		else:
			raise ValueError(f"Invalid controller type: {self.controller_type}")
		return generative_lm

	@staticmethod
	def _set_seed(seed: int) -> int:
		"""
		Set the random seed for reproducibility.

		Parameters:
			seed (int): The random seed to use for reproducibility.

		Returns:
			The random seed.
		"""
		random.seed(seed)
		np.random.seed(seed)
		torch.manual_seed(seed)
		return seed

	@property
	def thought_length(self) -> ResponseLength | None:
		return self._thought_length

	@thought_length.setter
	def thought_length(self, thought_length: ResponseLength | None) -> None:
		self._thought_length = thought_length

	@property
	def response_length(self) -> ResponseLength | None:
		return self._response_length

	@response_length.setter
	def response_length(self, response_length: ResponseLength | None) -> None:
		self._response_length = response_length

	@property
	def reasoning_field_name(self) -> str:
		"""Get the reasoning field name from the generator signature."""
		return self.generator.reasoning_field_name

	@property
	def verbosity(self) -> Verbosity:
		"""Get the current verbosity level."""
		return self._verbosity

	@verbosity.setter
	def verbosity(self, verbosity: Verbosity) -> None:
		"""
		Set the verbosity level for TreeOfThoughts and all its components.

		This updates the logger levels for:
		- TreeOfThoughts module
		- Generator module
		- Evaluator module
		- Controller module

		Parameters:
			verbosity (Verbosity): The new verbosity level to set.
		"""
		self._verbosity = verbosity

		# Set logger level for TreeOfThoughts
		logger.setLevel(VERBOSITY_TO_LOGGING_LEVEL[verbosity])

		# Update verbosity for all components
		self.generator.verbosity = verbosity
		self.evaluator.verbosity = verbosity
		self.controller.verbosity = verbosity

		# Set logger levels for component modules
		generator_logger = logging.getLogger("predict.generator.generator")
		evaluator_logger = logging.getLogger("predict.evaluator.evaluator")
		controller_logger = logging.getLogger("predict.controller.controller")

		for component_logger in [generator_logger, evaluator_logger, controller_logger]:
			component_logger.setLevel(VERBOSITY_TO_LOGGING_LEVEL[verbosity])

	def __init__(
		self,
		generator_signature: type[ReasoningSignature] | str,
		evaluator_signature: type[ReasoningSignature] | str | None = None,
		evaluator_signature_orm: type[ReasoningSignature] | str | None = None,
		evaluator_signature_prm: type[ReasoningSignature] | str | None = None,
		generative_lm: GenerativeLocalVLLM | None = None,
		reranker_lm: ScoringLocalVLLM | None = None,
		# Generator parameters
		thought_length: "ResponseLength | None" = None,
		response_length: "ResponseLength | None" = None,
		max_reasoning_steps: int = 10,
		final_output_kind: FINAL_OUTPUT_KIND_TYPE = "synthesis_faithful",
		# Controller parameters
		controller_type: Literal["generator", "reranker"] = "reranker",
		controller_tools: list[Callable | dspy.Tool] | None = None,
		action_space_paths: list[str | Path] | None = None,
		early_stopping_enabled: bool = True,
		finish_tool_description: str | None = None,
		forced_choice_function: Callable = return_action_if_single_option,
		# Evaluator parameters
		consider_reasoning_in_final_eval: bool = False,
		evaluator_type: Literal["generator", "programmatic", "reranker"] = "reranker",
		programmatic_prm_scorer: Callable[[ProgrammaticEvaluationInput], float] | None = None,
		programmatic_orm_scorer: Callable[[ProgrammaticEvaluationInput], float] | None = None,
		programmatic_prm_score_bounds: tuple[float, float] = (0.0, 1.0),
		programmatic_orm_score_bounds: tuple[float, float] = (0.0, 1.0),
		seed: int = 42,
		verbosity: Verbosity = Verbosity.INFO,
	) -> None:
		"""
		Initialize a Tree-of-Thoughts module and its configurable components.

		The primary task is specified in the generator signature. The inputs (`x`) are the input
		fields in the generator signature. The outputs (`y`) are the output fields in the generator signature. Reasoning steps (`z`) are the reasoning fields in the generator signature.

		There are two types of evaluators: Process Reward Model (PRM) & Outcome Reward Model (ORM).
		The PRM evaluates the quality of the reasoning steps. The ORM evaluates the quality of the final response.

		The PRM's input fields are the input fields from the generator signature and the reasoning
		steps so far (`Z_i`). The output fields of the PRM dictate the rubric for evaluating the
		quality of intermediate reasoning.

		The ORM's input fields are the input fields from the generator signature and the final
		response (`y`). The output fields of the ORM dictate the rubric for evaluating the quality
		of the final response.

		Users can either enter a single evaluator signature that generaizes to both PRM and ORM,
		or enter two separate evaluator signatures: one for PRM and one for ORM.

		Dimension weights in evaluators are specified directly in the evaluation signature's fields
		using the ``rubric_weight`` parameter in the OutputField() constructor. For example:

		```python
		soundness: int = dspy.OutputField(desc="...", ge=1, le=7, rubric_weight=0.7)
		promise: int = dspy.OutputField(desc="...", ge=1, le=7, rubric_weight=0.3)
		```

		If no ``rubric_weight`` is specified, equal weights are used for all dimensions.

		Args:
			generator_signature (ReasoningSignature | str): DSPy signature defining the task inputs,
				outputs, and reasoning fields.
			evaluator_signature (ReasoningSignature | str | None): DSPy signature for evaluating
				thoughts and final responses. Defaults to deriving an evaluator signature from the
				generator when ``None``. Use rubric_weight in OutputField() to specify dimension weights.
			evaluator_signature_orm (ReasoningSignature | str | None): DSPy signature for Outcome
				Reward Model (ORM) evaluation of final responses (optionally with reasoning).
				When ``None``, falls back to ``evaluator_signature``.
				Use rubric_weight in OutputField() to specify dimension weights.
			evaluator_signature_prm (ReasoningSignature | str | None): DSPy signature for Process
				Reward Model (PRM) evaluation of intermediate reasoning steps. When ``None``, falls
				back to ``evaluator_signature``.
				Use rubric_weight in OutputField() to specify dimension weights.
			generative_lm (GenerativeLocalVLLM | None): Pre-initialized language model instance for
				generator and evaluator components. Falls back to ``dspy.settings.lm`` when ``None``.
			reranker_lm (ScoringLocalVLLM | None): Pre-initialized language model instance for reranker
				controller. Required when controller_type is "reranker". Must be a ScoringLocalVLLM
				instance initialized for scoring tasks.
			thought_length (ResponseLength | None): Optional constraint on the length (defined via
			    words, sentences, etc...) of each intermediate thought produced by the generator.
			response_length (ResponseLength | None): Optional constraint on the length of final
				responses (defined via words, sentences, etc...) produced by the generator.
			max_reasoning_steps (int): Maximum number of reasoning steps the generator may
				take before producing a final response.
			final_output_kind (FINAL_OUTPUT_KIND_TYPE): Kind of final output instruction
				(synthesis_faithful, synthesis_strict, synthesis_restructured, conclusion).
				synthesis_faithful preserves all reasoning steps in final answer. synthesis_strict
				preserves all reasoning steps in final answer. synthesis_restructured
				preserves all reasoning steps in final answer. conclusion
				provides concise conclusion. Defaults to ``synthesis_faithful``.
			controller_type (Literal["generator", "reranker"]): Type of controller to use.
				"generator" uses a generator model to generate controller actions.
				"reranker" uses a reranker model to score and select controller actions.
				Defaults to ``"reranker"``.
			controller_tools (list[Callable | dspy.Tool] | None): Custom tools for the generative
				controller only. Can be used alone or combined with action_space_paths. Only
				applicable when controller_type is "generator".
			action_space_paths (list[str | Path] | None): Paths to action space JSON files. Each JSON
				defines a dimension (e.g., structure, style, or subtopic) with choices that can be
				selected. For the generative controller, creates ONE combined tool  with parameters
				for each dimension. For the reranker controller, creates one tool per unique
				combination of choices across dimensions (controller_tools not supported).
			early_stopping_enabled (bool): Whether the controller may terminate search early when a
				termination condition is met, or upon the controller's request.
				Defaults to ``True``.
			finish_tool_description (str | None): Optional custom description for the finish tool.
				If None, uses the default FINISH_TOOL description. This allows customizing when the
				controller should finish reasoning (e.g., requiring minimum reasoning depth or
				constraint verification actions before finishing).
			forced_choice_function (Callable): Handler used when the controller must choose from a
				single available action. Defaults to ``return_action_if_single_option``.
			consider_reasoning_in_final_eval (bool): Whether the evaluator should consider the
				sequence of reasoning steps alongside the final response. Defaults to ``True``.
			evaluator_type (Literal["generator", "programmatic", "reranker"]): Evaluator type to
				use. "generator" uses an LM judge, "programmatic" uses Python scorers, and
				"reranker" uses a reranker model. Defaults to ``"reranker"``.
			programmatic_prm_scorer: Optional PRM scorer for programmatic evaluation.
			programmatic_orm_scorer: Optional ORM scorer for programmatic evaluation.
			programmatic_prm_score_bounds: Bounds for normalizing PRM scores to [0, 1].
			programmatic_orm_score_bounds: Bounds for normalizing ORM scores to [0, 1].
			generative_lm_gpu_id (int): GPU ID to use for the generative model. Used when
				initializing models with GPU assignment. Defaults to ``0``.
			reranker_lm_gpu_id (int): GPU ID to use for the reranker model. Used when initializing
				models with GPU assignment. Only relevant when controller_type is RERANKER.
				Defaults to ``1``.
			seed (int): Random seed used to make generation deterministic across runs. Defaults to
				``42``.
			verbosity (Verbosity): Verbosity level for logging across generator, evaluator, and
				controller operations. Must be a Verbosity enum value (DEBUG, INFO, WARNING, ERROR).
				Defaults to ``Verbosity.INFO``.
		"""
		super().__init__()
		action_space_paths = action_space_paths or None  # Normalize empty lists to None.
		self.generator_signature = generator_signature
		self.evaluator_signature = evaluator_signature
		self.evaluator_signature_orm = evaluator_signature_orm
		self.evaluator_signature_prm = evaluator_signature_prm
		self.controller_tools = controller_tools
		self.action_space_paths = action_space_paths
		self.controller_type = controller_type
		self.evaluator_type = evaluator_type
		self.seed = self._set_seed(seed=seed)
		self._verbosity = verbosity

		# Set logger level based on verbosity
		logger.setLevel(VERBOSITY_TO_LOGGING_LEVEL[verbosity])

		# Constraints
		self._thought_length = thought_length
		self._response_length = response_length

		# Initialize ToT components
		self.generator = TreeOfThoughtGenerator(
			signature=ensure_reasoning_signature(generator_signature),
			max_reasoning_steps=max_reasoning_steps,
			thought_length=thought_length,
			response_length=response_length,
			verbosity=verbosity,
			final_output_kind=final_output_kind,
			# TODO[P2]: Add support for providing a generator-specific configuration.
		)
		if evaluator_type == "generator":
			self.evaluator = TreeOfThoughtEvaluator(
				generator_signature=ensure_reasoning_signature(generator_signature),
				evaluator_signature=(
					ensure_reasoning_signature(evaluator_signature)
					if evaluator_signature is not None
					else None
				),
				evaluator_signature_orm=(
					ensure_reasoning_signature(evaluator_signature_orm)
					if evaluator_signature_orm is not None
					else None
				),
				evaluator_signature_prm=(
					ensure_reasoning_signature(evaluator_signature_prm)
					if evaluator_signature_prm is not None
					else None
				),
				consider_reasoning_in_final_eval=consider_reasoning_in_final_eval,
				verbosity=verbosity,
			)
		elif evaluator_type == "programmatic":
			self.evaluator = TreeOfThoughtProgrammaticEvaluator(
				generator_signature=ensure_reasoning_signature(generator_signature),
				prm_scorer=programmatic_prm_scorer,
				orm_scorer=programmatic_orm_scorer,
				consider_reasoning_in_final_eval=consider_reasoning_in_final_eval,
				prm_score_bounds=programmatic_prm_score_bounds,
				orm_score_bounds=programmatic_orm_score_bounds,
				verbosity=verbosity,
			)
		else:
			if reranker_lm is None:
				raise ValueError(
					"reranker_lm must be provided when evaluator_type is RERANKER. "
					"Please initialize a ScoringLocalVLLM and pass it as reranker_lm."
				)
			self.evaluator = TreeOfThoughtRerankerEvaluator(
				generator_signature=ensure_reasoning_signature(generator_signature),
				evaluator_signature=(
					ensure_reasoning_signature(evaluator_signature)
					if evaluator_signature is not None
					else None
				),
				evaluator_signature_orm=(
					ensure_reasoning_signature(evaluator_signature_orm)
					if evaluator_signature_orm is not None
					else None
				),
				evaluator_signature_prm=(
					ensure_reasoning_signature(evaluator_signature_prm)
					if evaluator_signature_prm is not None
					else None
				),
				consider_reasoning_in_final_eval=consider_reasoning_in_final_eval,
				verbosity=verbosity,
			)

		# Initialize controller based on controller_type
		if controller_type == "reranker":
			# For reranker controller, reranker_lm must be provided
			if reranker_lm is None:
				raise ValueError(
					"reranker_lm must be provided when controller_type is RERANKER. "
					"Please initialize a ScoringLocalVLLM and pass it as reranker_lm."
				)
			# Reranker controller only supports action_space_paths (not custom tools)
			if controller_tools is not None:
				raise ValueError(
					"controller_tools is not supported for RERANKER controller type. "
					"Use action_space_paths instead to define the action space via JSON files."
					"Alternatively, use a generative controller with controller_tools."
				)

			self.controller = TreeOfThoughtsControllerReranker(
				signature=ensure_reasoning_signature(generator_signature),
				max_reasoning_steps=max_reasoning_steps,
				action_space_paths=action_space_paths,
				forced_choice_function=forced_choice_function,
				early_stopping_enabled=early_stopping_enabled,
				finish_tool_description=finish_tool_description,
				verbosity=verbosity,
			)
		else:
			self.controller = TreeOfThoughtsController(
				signature=ensure_reasoning_signature(generator_signature),
				max_reasoning_steps=max_reasoning_steps,
				tools=controller_tools,
				action_space_paths=action_space_paths,
				forced_choice_function=forced_choice_function,
				early_stopping_enabled=early_stopping_enabled,
				finish_tool_description=finish_tool_description,
				verbosity=verbosity,
			)

		self.lm = self._set_lm(generative_lm, reranker_lm)

	@staticmethod
	def assert_valid_parameters(tot_parameters: TreeOfThoughtsParameters) -> None:
		"""Validate the correctness of provided TreeOfThoughtsParameters.

		Parameters:
			tot_parameters: The parameters to validate.

		Raises:
			AssertionError: If any parameter is invalid (e.g., out of range or inconsistent).
		"""
		# ruff: noqa: E501 (ignore long lines -- assertions need not be super readable)
		# TODO[P3]: Adjust assertions based on the underlying language model that DSPy is using.
		# 	If using OpenAI or Google models, then temperature should be between 0 and 2.
		# 	If using Anthropic models, then temperature should be between 0 and 1.
		# May need to add an additional parameter, or access the DSPy configuration to determine the underlying language model.
		assert tot_parameters.top_k > 0, "`top_k` must be greater than 0"
		assert tot_parameters.n_samples_judge > 0, "`n_samples_judge` must be greater than 0"
		assert tot_parameters.n_samples_generation > 0, f"`n_samples_generation` must be greater than 0, but got {tot_parameters.n_samples_generation}"
		assert 0 <= tot_parameters.judge_temperature <= 2, f"`judge_temperature` must be between 0 and 2, but got {tot_parameters.judge_temperature}"
		assert 0 <= tot_parameters.generator_temperature <= 2, f"`generator_temperature` must be between 0 and 2, but got {tot_parameters.generator_temperature}"
		assert tot_parameters.depth > 0, f"depth must be greater than 0, but got {tot_parameters.depth}"
		assert tot_parameters.num_final_candidates > 0, f"`num_final_candidates` must be greater than 0, but got {tot_parameters.num_final_candidates}"
		max_final_candidates = tot_parameters.top_k * tot_parameters.n_samples_generation
		if tot_parameters.do_pruning:
			assert tot_parameters.num_final_candidates <= max_final_candidates, f"`num_final_candidates` ({tot_parameters.num_final_candidates}) must be less than or equal to `top_k` * `n_samples_generation` ({max_final_candidates})"
		# When top_k_first is set, layer 1 uses top_k_first (not top_k), and layer 2+ has
		# n_samples * top_k_first candidates to select from. Only require n_samples >= top_k
		# when top_k_first is not set.
		if tot_parameters.top_k_first is None:
			assert tot_parameters.n_samples_generation >= tot_parameters.top_k, f"`n_samples_generation` must be greater than or equal to `top_k`, but got {tot_parameters.n_samples_generation} < {tot_parameters.top_k}"
		if tot_parameters.top_k_first is not None:
			assert tot_parameters.top_k_first > 0, "`top_k_first` must be greater than 0"
			assert tot_parameters.n_samples_generation >= tot_parameters.top_k_first, (
				f"`n_samples_generation` must be >= `top_k_first`, "
				f"but got {tot_parameters.n_samples_generation} < {tot_parameters.top_k_first}"
			)
			assert tot_parameters.n_samples_generation * tot_parameters.top_k_first >= tot_parameters.top_k, (
				f"`n_samples_generation * top_k_first` must be >= `top_k`, "
				f"but got {tot_parameters.n_samples_generation * tot_parameters.top_k_first} < {tot_parameters.top_k}"
			)

	def _select_with_random_ties(
		self,
		candidates: list[Node],
		top_k: int,
	) -> list[Node]:
		"""Select top-k nodes with random tie-breaking.

		When multiple nodes have the same score, randomly select among them
		instead of preserving deterministic order.

		Parameters:
			candidates: List of nodes to select from (should not be pruned)
			top_k: Number of nodes to select

		Returns:
			List of selected nodes, sorted by index
		"""
		# Group nodes by score
		score_groups: dict[float, list[Node]] = defaultdict(list)
		for node in candidates:
			score = node.score if node.score is not None else float('-inf')
			score_groups[score].append(node)

		# Sort score tiers descending
		sorted_scores = sorted(score_groups.keys(), reverse=True)

		# Select nodes, randomly sampling within each tier
		selected = []
		for score in sorted_scores:
			tier_nodes = score_groups[score]
			if len(selected) + len(tier_nodes) <= top_k:
				# All nodes in this tier fit - take them all
				selected.extend(tier_nodes)
			else:
				# Need to randomly sample from this tier
				needed = top_k - len(selected)
				sampled = random.sample(tier_nodes, needed)
				selected.extend(sampled)
				break

		# Sort by index for consistent ordering
		return sorted(selected, key=lambda node: node.index)

	def _create_responses_with_self_consistency(self, best_nodes: list[Node]) -> list[Response]:
		"""Create responses using self-consistency (aggregate by frequency).

		Parameters:
			best_nodes: Nodes sorted by score (highest first).

		Returns:
			List of Response objects.
		"""
		assert all(node.state.output for node in best_nodes), (
			"All nodes must have a final response to use self-consistency."
		)
		# Group nodes by their output string (excluding metadata like `error`)
		answer_nodes: dict[str, list[Node]] = {}
		for node in best_nodes:
			output_data = self._extract_output_fields(node.state.output)
			output_str = stringify(output_data)
			if output_str not in answer_nodes:
				answer_nodes[output_str] = []
			answer_nodes[output_str].append(node)
		# Sort by frequency (most common answers first)
		sorted_answers = sorted(answer_nodes.items(), key=lambda item: len(item[1]), reverse=True)
		responses = []
		for _, nodes in sorted_answers:
			responses.append(Response.from_dict(self._extract_output_fields(nodes[0].state.output)))
		return responses

	def _extract_output_fields(self, output: dict[str, Any]) -> dict[str, Any]:
		"""
		Extract only the generator signature's output fields from a node output dict.

		We attach metadata like `error` to node outputs so downstream validity checks can
		prune failed generations/parses. That metadata must not leak into exported strings.
		"""
		allowed = set(self.generator.signature.output_fields.keys())
		extracted = {k: v for k, v in (output or {}).items() if k in allowed}
		assert extracted, (
			"Final output node is missing expected output fields. "
			f"Allowed={sorted(allowed)} OutputKeys={sorted((output or {}).keys())}"
		)
		return extracted

	def _validate_output(
		self,
		responses: list[Response],
		response_strings: list[str],
		reasoning_chains: list[ReasoningChain],
	) -> None:
		"""Validate that output components are consistent and non-empty.

		Parameters:
			responses: List of Response objects.
			response_strings: List of response strings.
			reasoning_chains: List of ReasoningChain objects.

		Raises:
			AssertionError: If validation fails.
		"""
		assert len(responses) > 0, "No responses to return"
		assert len(response_strings) > 0, "No response strings to return"
		assert len(responses) == len(response_strings) == len(reasoning_chains), (
			f"Mismatch: {len(responses)} responses, {len(response_strings)} response_strings, {len(reasoning_chains)} reasoning_chains"
		)

	def create_output(
		self,
		candidates: list[Node],
		tree: Tree,
		tot_parameters: TreeOfThoughtsParameters,
		start_time: float,
	) -> TreeOfThoughtsOutput:
		"""Create the output prediction from candidate (leaf) nodes in the tree.

		Selects the top candidates, extracts their responses and reasoning chains,
		and constructs a TreeOfThoughtsOutput with metadata.

		Parameters:
			candidates: Nodes representing candidates for final response(s).
			tree: The reasoning tree structure.
			tot_parameters: Configuration parameters for tree search.
			start_time: Unix timestamp when tree execution began.

		Returns:
			TreeOfThoughtsOutput containing responses, reasoning chains, tree structure,
			and runtime metadata.
		"""
		best_nodes = sorted(
			candidates,
			key=lambda node: node.score if node.score is not None else float('-inf'),
			reverse=True
		)
		responses = (
			self._create_responses_with_self_consistency(best_nodes)
			if tot_parameters.use_self_consistency
			else [Response.from_dict(self._extract_output_fields(node.state.output)) for node in best_nodes]
		)
		response_strings = [stringify(response.to_dict()) for response in responses]

		# Select final candidates using the same strategy as thought selection
		if len(best_nodes) > tot_parameters.num_final_candidates:
			# Use select_nodes with num_to_select parameter
			# Don't mark non-selected output nodes as pruned (they're valid candidates, just not top-k)
			selected_nodes = self.select_nodes(
				judged_nodes=best_nodes,
				tot_parameters=tot_parameters,
				num_to_select=tot_parameters.num_final_candidates,
				mark_non_selected_as_pruned=False,
			)

			# Map back to responses using node indices
			selected_indices = {node.index for node in selected_nodes}
			selected_pairs = [
				(node, resp, resp_str)
				for node, resp, resp_str in zip(best_nodes, responses, response_strings, strict=True)
				if node.index in selected_indices
			]
			best_nodes = [pair[0] for pair in selected_pairs]
			responses = [pair[1] for pair in selected_pairs]
			response_strings = [pair[2] for pair in selected_pairs]

		reasoning_chains = [
			ReasoningChain.from_node_path(tree.get_path_to_node(node)) for node in best_nodes
		]
		self._validate_output(responses, response_strings, reasoning_chains)
		self._log_final_output(responses, response_strings, reasoning_chains)

		return TreeOfThoughtsOutput(
			responses=responses,
			reasoning_steps=reasoning_chains,
			response_strings=response_strings,
			tree=tree,
			runtime=time.time() - start_time,
		)

	def _log_final_output(
		self,
		responses: list[Response],
		response_strings: list[str],
		reasoning_chains: list[ReasoningChain],
	) -> None:
		"""Log final output summary including responses and reasoning chains.

		Parameters:
			responses: List of Response objects.
			response_strings: List of response strings.
			reasoning_chains: List of ReasoningChain objects.
		"""
		logger.debug("\n" + "=" * 80)
		logger.debug("FINAL OUTPUT SUMMARY")
		logger.debug("=" * 80)
		logger.debug(f"Produced {len(responses)} responses")

		for i, (response_str, reasoning_chain) in enumerate(
			zip(response_strings, reasoning_chains, strict=True), 1
		):
			logger.debug(f"\n--- Final Response {i} ---")
			logger.debug(f"\n{response_str}")
			if reasoning_chain.nodes:
				logger.debug(f"\nReasoning chain ({len(reasoning_chain.nodes)} nodes):")
				logger.debug(str(reasoning_chain))
			logger.debug("-" * 80)
		logger.debug("=" * 80 + "\n")

	def _get_output_text(self, output: dict[str, Any] | None) -> str | None:
		"""Extract a string representation from output dictionary.

		Parameters:
			output: Output dictionary or None.

		Returns:
			String representation of output, or None if not found.
		"""
		if not output:
			return None
		for _, value in output.items():
			if isinstance(value, str) and len(value) > 20:
				return value
		return stringify(output)

	def _get_step_value(self, step: dict[str, Any]) -> str:
		"""Extract string value from a reasoning step.

		Parameters:
			step: Reasoning step (dict).

		Returns:
			String representation of the step.
		"""
		if self.reasoning_field_name in step:
			return str(step[self.reasoning_field_name]).strip()
		error = step.get("error")
		assert isinstance(error, ExecutionError) and error.has_error(), (
			f"Missing reasoning field '{self.reasoning_field_name}' in step: {step}"
		)
		return error.error_message or "Generation failed."

	def _log_generated_nodes(self, new_nodes: list[Node]) -> None:
		"""Log information about generated candidate nodes.

		Parameters:
			new_nodes: List of newly generated nodes.
		"""
		assert len(new_nodes) > 0, "No new nodes to log"
		layer = new_nodes[0].layer
		logger.debug(format_step_info(layer=layer,message=f"Generated {len(new_nodes)} nodes"))
		for node in new_nodes:
			reasoning_steps = node.state.reasoning
			has_output = bool(node.state.output)

			# Prepare reasoning content strings
			reasoning_content = []
			if reasoning_steps and not has_output:
				for step in reasoning_steps:
					reasoning_content.append(self._get_step_value(step))

			logger.debug(
				format_generated_node_log(
					layer=layer,
					node_index=node.index,
					parent_id=node.parent_id,
					reasoning_steps_count=len(reasoning_steps),
					has_output=has_output,
					reasoning_content=reasoning_content,
					output_text=self._get_output_text(node.state.output),
				)
			)

	def _log_evaluated_nodes(self, judged_nodes: list[Node]) -> None:
		"""Log information about evaluated nodes.

		Parameters:
			judged_nodes: List of evaluated nodes with scores.
		"""
		assert len(judged_nodes) > 0, "No judged nodes to log"
		for node in judged_nodes:
			logger.debug(format_step_info(layer=node.layer, node_index=node.index, score=node.score))

	def _log_selected_nodes(self, frontier: list[Node]) -> None:
		"""Log information about selected nodes for the next frontier.

		Parameters:
			frontier: List of selected nodes forming the new frontier.
		"""
		if len(frontier) == 0:
			logger.debug("[Step] No nodes selected for next frontier.")
			return
		logger.debug(
			format_step_info(
				layer=frontier[0].layer, message=f"Selected {len(frontier)} nodes for next frontier",
			)
		)
		for node in frontier:
			logger.debug(
				format_step_info(layer=node.layer, node_index=node.index, score=node.score)
			)

	def _log_controller_decisions(self, frontier: list[Node]) -> None:
		"""Log controller decisions for parent nodes in the frontier.

		These controller outputs were generated by the controller and stored in each parent node's
		state.controller_outputs. They will be used to generate children from each parent.

		Parameters:
			frontier: List of nodes in the frontier.
		"""
		assert len(frontier) > 0, "No frontier nodes to log"
		layer = frontier[0].layer
		for node in frontier:
			if node.state.controller_outputs:
				controller_outputs = node.state.controller_outputs
				logger.debug(
					format_step_info(
						layer=layer,
						node_index=node.index,
						message=f"{len(controller_outputs)} controller output(s)",
					)
				)
				for j, controller_output in enumerate(controller_outputs, 1):
					formatted_output = format_controller_output(
	controller_output, j
					)
					logger.debug(f"\t{formatted_output}")

	def forward(
		self,
		state: Input,
		tot_parameters: TreeOfThoughtsParameters,
		generator_demos: list[dict[str, Any]] | None = None,
		controller_demos: list[dict[str, Any]] | None = None,
		evaluator_demos: list[dict[str, Any]] | None = None,
		evaluator_demos_prm: list[dict[str, Any]] | None = None,
		evaluator_demos_orm: list[dict[str, Any]] | None = None,
		forced_controller_choices: dict[tuple[int, int], list[dict[str, Any]]] | None = None,
		do_save_tree: bool = False,
		outputs_directory: str | None = None,
		outputs_filename: str | None = None,
	) -> TreeOfThoughtsOutput:
		"""Execute Tree-Of-Thoughts search to generate reasoning and responses.

		This method orchestrates the complete tree search process:
		1. Initialize the tree with the input state
		2. Iteratively expand the frontier through planning, generation, evaluation, and selection
		3. Generate final responses from the best reasoning chains
		4. Return the results with metadata (runtime, tree structure)

		Parameters:
			state: An input task for which we want to generate a response. This is a dictionary
				mapping input fields to their values (e.g., {"problem": "...", "context": "..."}).
			tot_parameters: The hyper-parameters for Tree-Of-Thoughts search.
			generator_demos: Optional demos to guide the generator.
			controller_demos: Optional demos to guide the controller.
			evaluator_demos: Optional demos to guide the evaluator (used for both PRM and ORM
				if specific demos are not provided).
			evaluator_demos_prm: Optional demos specifically for PRM evaluation.
			evaluator_demos_orm: Optional demos specifically for ORM evaluation.
			forced_controller_choices: Optional dict mapping (depth, node_position_in_layer) tuples
				to lists of pre-specified controller action dicts. Used for testing/debugging to
				force specific controller decisions at particular tree positions. Each action dict
				should contain 'action', 'action_arguments', and 'considerations' fields.
			do_save_tree: Whether to save the tree to a file.
			outputs_directory: Directory path for saving tree (if do_save_tree=True).
			outputs_filename: Filename for saved tree (if do_save_tree=True).

		Returns:
			TreeOfThoughtsOutput containing responses, reasoning chains, tree structure,
			and runtime metadata.
		"""
		start_time = time.time()
		generator_input_fields = self.generator.signature.input_fields.keys()
		assert all(field in state for field in generator_input_fields), (
			f"Missing input fields in state.\nRequired fields: {generator_input_fields}. "
			f"Provided fields: {state.keys()}"
		)
		self.assert_valid_parameters(tot_parameters=tot_parameters)

		# Initialize tree with root node
		tree: Tree = Tree.model_validate({NodeField.STATE: state})
		frontier: list[Node] = [tree.root]

		max_intermediate_reasoning_steps = tot_parameters.depth
		reasoning_steps = tqdm(
			iterable=range(max_intermediate_reasoning_steps+1),
			disable=self.verbosity not in (Verbosity.DEBUG, Verbosity.INFO)
		)

		# Iteratively expand the tree with intermediate reasoning steps
		# Continue until nodes reach the maximum depth (layer == depth)
		# Root is at layer 0, so after depth reasoning steps, nodes will be at layer depth
		while (
			len(frontier) > 0
			and frontier[0].layer < max_intermediate_reasoning_steps
			and not all(node.state.output or node.is_pruned for node in frontier)
		):
			reasoning_steps.set_description(f"Reasoning step (layer) #{frontier[0].layer + 1}")

			new_frontier: list[Node] = self.step(
				frontier=frontier,
				tree=tree,
				tot_parameters=tot_parameters,
				generator_demos=generator_demos,
				controller_demos=controller_demos,
				evaluator_demos=evaluator_demos,
				evaluator_demos_prm=evaluator_demos_prm,
				evaluator_demos_orm=evaluator_demos_orm,
				forced_controller_choices=forced_controller_choices,
			)
			reasoning_steps.update(1)
			frontier = new_frontier

		# Generate final responses after exceeding the max_intermediate_reasoning_steps limit.
		# Force final output generation by setting controller_outputs to finish action
		if len(frontier) > 0 and not all(node.state.output or node.is_pruned for node in frontier):
			reasoning_steps.set_description("Final reasoning step")
			# Set controller outputs to force final generation for nodes without output
			n_final_candidates = (
				tot_parameters.n_final_responses_per_trajectory
				if tot_parameters.n_final_responses_per_trajectory is not None
				else tot_parameters.n_samples_generation
			)
			for node in frontier:
				if not node.state.output:
					controller_output = ControllerOutput(
						action="finish",
						action_arguments={},
						tool_descriptions="Action Name: finish",
						continue_reasoning=False,
						considerations="Max reasoning steps reached - generating final response",
						internal_reasoning="",
						prefix="",
						unique_action_response_count=n_final_candidates,
					)
					node.state.controller_outputs = [controller_output]
			# Enable pruning to identify top-k scoring nodes for final response
			original_do_pruning = tot_parameters.do_pruning
			tot_parameters.do_pruning = True
			frontier = self.step(
				frontier=frontier,
				tree=tree,
				tot_parameters=tot_parameters,
				generator_demos=generator_demos,
				controller_demos=controller_demos,
				evaluator_demos=evaluator_demos,
				evaluator_demos_prm=evaluator_demos_prm,
				evaluator_demos_orm=evaluator_demos_orm,
				forced_controller_choices=forced_controller_choices,
			)
			tot_parameters.do_pruning = original_do_pruning
			reasoning_steps.update(1)

		# Candidates are nodes with final output and scores that haven't been pruned
		candidates = [
			node for node in tree.nodes.values()
			if node.state.output and node.score is not None and not node.is_pruned
		]
		reasoning_steps.close()

		# Create output from best candidates
		assert len(candidates) > 0, f"No candidates found. Tree has {len(tree.nodes)} nodes."
		output: TreeOfThoughtsOutput = self.create_output(
			candidates=candidates,
			tree=tree,
			tot_parameters=tot_parameters,
			start_time=start_time,
		)
		if do_save_tree:
			log_tree_run(
				tree=tree,
				tot_parameters=tot_parameters,
				tot_output=output,
				directory_path=outputs_directory,
				file_name=outputs_filename,
			)
		return output

	def step(
		self,
		frontier: list[Node],
		tree: Tree,
		tot_parameters: TreeOfThoughtsParameters,
		generator_demos: list[dict[str, Any]] | None = None,
		controller_demos: list[dict[str, Any]] | None = None,
		evaluator_demos: list[dict[str, Any]] | None = None,
		evaluator_demos_prm: list[dict[str, Any]] | None = None,
		evaluator_demos_orm: list[dict[str, Any]] | None = None,
		forced_controller_choices: dict[tuple[int, int], list[dict[str, Any]]] | None = None,
	) -> list[Node]:
		"""
		Perform a step in Tree-Of-Thoughts to generate reasoning steps for the next layer.

		This method orchestrates the four main phases of tree search:
		1. **Planning**: Call the controller to determine actions for each node
		2. **Generation**: Generate new reasoning steps for each node in the frontier
		3. **Evaluation**: Score the generated reasoning steps
		4. **Selection**: Select the top-k nodes to continue to the next layer

		Parameters:
			frontier: Nodes to expand in this step.
			tree: Current tree structure.
			tot_parameters: Tree search configuration parameters.
			generator_demos: Optional demos to guide generator.
			controller_demos: Optional demos to guide controller.
			evaluator_demos: Optional demos for evaluator (used for both PRM and ORM
				if specific demos not provided).
			evaluator_demos_prm: Optional demos specifically for PRM evaluation.
			evaluator_demos_orm: Optional demos specifically for ORM evaluation.
			forced_controller_choices: Optional dict mapping tree positions to forced controller actions.

		Returns:
			List of nodes forming the new frontier for the next layer (top-k selected nodes).
		"""
		assert len(frontier) > 0, "No frontier nodes to plan actions"
		logger.debug(
			format_step_info(layer=frontier[0].layer, message=f"{len(frontier)} nodes in frontier")
		)

		# Phase 1: Planning - Controller decisions
		frontier = self.plan_actions(
			frontier=frontier,
			tot_parameters=tot_parameters,
			controller_demos=controller_demos,
			forced_controller_choices=forced_controller_choices,
		)
		self._log_controller_decisions(frontier)

		# Phase 2: Generation - Create candidate nodes for next layer (reasoning/final answers)
		new_nodes: list[Node] = self.generate_thoughts(
			frontier=frontier,
			tree=tree,
			tot_parameters=tot_parameters,
			generator_demos=generator_demos,
		)
		self._log_generated_nodes(new_nodes)

		if tot_parameters.do_pruning:
			judged_nodes: list[Node] = self.evaluate_thoughts(
				frontier=new_nodes,
				tree=tree,
				tot_parameters=tot_parameters,
				demos=evaluator_demos,
				demos_prm=evaluator_demos_prm,
				demos_orm=evaluator_demos_orm,
			)
			self._log_evaluated_nodes(judged_nodes)

			# Phase 4: Selection - Keep only the top-k nodes for the next layer
			# Filter out nodes that have final outputs as they cannot be expanded further.
			# Also filter out pruned nodes (e.g., failed parsing/failed generation).
			eligible_nodes = [
				node for node in judged_nodes if not node.state.output and not node.is_pruned
			]

			frontier = self.select_nodes(
				judged_nodes=eligible_nodes,
				tot_parameters=tot_parameters,
			)
			self._log_selected_nodes(frontier)

			return frontier
		else:
			# No pruning - but still need to evaluate nodes with final outputs
			# so they can be selected as candidates (they need scores)
			nodes_with_outputs = [node for node in new_nodes if node.state.output]
			if nodes_with_outputs:
				judged_output_nodes: list[Node] = self.evaluate_thoughts(
					frontier=nodes_with_outputs,
					tree=tree,
					tot_parameters=tot_parameters,
					demos=evaluator_demos,
					demos_prm=evaluator_demos_prm,
					demos_orm=evaluator_demos_orm,
				)
				self._log_evaluated_nodes(judged_output_nodes)
				# Update new_nodes with scored versions
				scored_output_dict = {node.index: node for node in judged_output_nodes}
				for i, node in enumerate(new_nodes):
					if node.index in scored_output_dict:
						new_nodes[i] = scored_output_dict[node.index]
			# Return all generated nodes (excluding final outputs)
			return [node for node in new_nodes if not node.state.output]

	def generate_thoughts(
		self,
		frontier: list[Node],
		tree: Tree,
		tot_parameters: TreeOfThoughtsParameters,
		generator_demos: list[dict[str, Any]] | None = None,
	) -> list[Node]:
		"""Generate new reasoning steps for each node in the frontier.

		Creates child nodes by calling the generator on each frontier node state.
		For final-step nodes, ensures controller intervention signals answer generation.

		Parameters:
			frontier: Nodes to generate thoughts for.
			tree: Current tree structure.
			tot_parameters: Tree search configuration parameters.
			generator_demos: Optional demos to guide generator.

		Returns:
			List of newly generated child nodes.
		"""
		new_nodes = []
		# Filter out nodes that contain final responses
		filtered_frontier = [node for node in frontier if not node.state.output]

		generator_sampling_params: dict[str, Any] = {}
		generator_sampling_params["temperature"] = tot_parameters.generator_temperature
		generator_sampling_params["max_tokens"] = tot_parameters.generator_max_tokens
		generator_sampling_params["top_p"] = tot_parameters.generator_top_p
		generator_sampling_params["top_k"] = tot_parameters.generator_top_k
		generator_sampling_params["min_p"] = tot_parameters.generator_min_p
		if tot_parameters.generator_use_beam_search:
			generator_sampling_params["use_beam_search"] = True

		# Create child nodes for each node in the fronter
		try:
			generator_predictions: list[list[dspy.Prediction]] = self.generator(
				states=[node.state for node in filtered_frontier],
				n_samples_generation=tot_parameters.n_samples_generation,
				demos=generator_demos,
				**generator_sampling_params,
			)
		except Exception as e:
			# If generator fails entirely (e.g., all trajectories too long), create error nodes
			# for all frontier nodes so the tree can continue with other branches
			error_msg = str(e)
			logger.warning(
				f"Generator failed for {len(filtered_frontier)} frontier node(s): "
				f"{error_msg[:200]}..."
			)
			# Create error nodes for each parent in the frontier
			# Always create n_samples_generation failed child nodes per parent
			for parent in filtered_frontier:
				for _ in range(tot_parameters.n_samples_generation):
					child_node = tree.create_child_node(
						parent_node=parent,
						output={
							self.generator.reasoning_field_name: error_msg,
							"error": ExecutionError(
								error_type="generation", raw_output=None, error_message=error_msg,
							),
						},
						controller_output=ControllerOutput(
							action="prune",
							action_arguments={},
							tool_descriptions="Action Name: prune",
							continue_reasoning=False,
							considerations="Generator failed - pruning node",
							internal_reasoning="",
							prefix="",
						),
					)
					# Automatically handle error nodes: set score to 0, mark as pruned
					child_node.score = 0.0
					child_node.is_pruned = True
					new_nodes.append(child_node)

			tree.add_layer(new_nodes)
			return new_nodes

		for parent, predictions in zip(
			filtered_frontier, generator_predictions, strict=True
		):
			# Map predictions to controller outputs, accounting for deduplicated actions
			# The controller deduplicates identical actions and stores unique_action_response_count
			# controller_outputs contains the current expansion options (both choices and interventions)
			choices_for_children = []
			for controller_output in parent.state.controller_outputs:
				count = controller_output.unique_action_response_count
				# Replicate this output 'count' times (one for each child it generated)
				choices_for_children.extend([controller_output] * count)

			for child_idx, child_candidate in enumerate(predictions):
				controller_output: ControllerOutput = choices_for_children[child_idx]
				if controller_output.action == "prune":
					error_msg = controller_output.tool_execution_error or "Controller failure."
					output = {
						self.generator.reasoning_field_name: error_msg,
						"error": ExecutionError(
							error_type="parsing",
							raw_output=None,
							error_message=error_msg,
						),
					}
					child_node = tree.create_child_node(
						parent_node=parent, output=output, controller_output=controller_output,
					)
					# Automatically handle error nodes: set score to 0, mark as pruned
					child_node.score = 0.0
					child_node.is_pruned = True
					new_nodes.append(child_node)
					continue

				# Extract fields from Prediction object
				# The generator returns either reasoning fields (for intermediate steps)
				# or output fields (for final answers), depending on continue_reasoning
				output_dict = {}

				# First try reasoning fields (for intermediate reasoning steps)
				for field_name in self.generator.signature.reasoning_fields.keys():
					if hasattr(child_candidate, field_name):
						output_dict[field_name] = getattr(child_candidate, field_name)

				if not output_dict:
					for field_name in self.generator.signature.output_fields.keys():
						if hasattr(child_candidate, field_name):
							output_dict[field_name] = getattr(
								child_candidate, field_name
							)

				# Preserve adapter-provided error metadata so downstream validity checks don't KeyError.
				# Important: this is metadata only; rendering/serialization code should filter it out
				# before sending back into the model.
				err = getattr(child_candidate, "error", ExecutionError())
				if err is None:
					err = ExecutionError()
				assert isinstance(err, ExecutionError), f"Expected ExecutionError, got {type(err)}"
				output_dict["error"] = err

				# If output_dict only has error (no actual content), we need to add a placeholder
				# field based on continue_reasoning to ensure the node has proper structure
				has_content = any(
					key != "error" for key in output_dict.keys()
				)
				if not has_content and err.has_error():
					# Error-only completion - add placeholder based on controller decision
					error_msg = err.error_message or "Generation failed"
					if controller_output.continue_reasoning:
						# Should have reasoning field(s) - use error message as placeholder for all
						for reasoning_field_name in self.generator.signature.reasoning_fields.keys():
							output_dict[reasoning_field_name] = error_msg
					else:
						# Should have output field(s) - use error message as placeholder for all
						for output_field_name in self.generator.signature.output_fields.keys():
							output_dict[output_field_name] = error_msg

				child_node = tree.create_child_node(
					parent_node=parent,
					output=output_dict,
					controller_output=controller_output,
				)

				# Automatically handle nodes with errors: set score to 0, mark as pruned, skip evaluation
				if err.has_error():
					child_node.score = 0.0
					child_node.is_pruned = True

				new_nodes.append(child_node)
		tree.add_layer(new_nodes)
		return new_nodes

	def _get_states_and_validity(self, frontier: list[Node]) -> tuple[list[State], list[bool]]:
		"""
		Helper function to extract states and determine validity based on parsing status.

		Args:
			frontier: List of nodes to check.

		Returns:
			Tuple containing:
				- List of states corresponding to the frontier nodes.
				- List of booleans indicating whether each node is valid (True) or failed
					parsing (False).
		"""
		states = []
		is_valid = []
		for node in frontier:
			states.append(node.state)
			# Check if the node is already pruned or if the most recent step indicates failure
			is_failed = node.is_pruned
			if not is_failed:
				if node.state.output:
					error: ExecutionError = node.state.output.get("error", ExecutionError())
					if error.has_error():
						is_failed = True
				else:
					reasoning_steps = node.state.reasoning
					if reasoning_steps:
						last_step = reasoning_steps[-1]
						error = last_step.get("error", ExecutionError())
						if error.has_error():
							is_failed = True
			is_valid.append(not is_failed)
		return states, is_valid

	def evaluate_thoughts(
		self,
		frontier: list[Node],
		tree: Tree,
		tot_parameters: TreeOfThoughtsParameters,
		demos: list[dict[str, Any]] | None = None,
		demos_prm: list[dict[str, Any]] | None = None,
		demos_orm: list[dict[str, Any]] | None = None,
	) -> list[Node]:
		"""Evaluate quality of reasoning steps in the frontier.

		Computes a score for each node in the frontier. The Evaluator computes the score in one of
		the following ways:
			1. Producing a single score (float) between a specified range (e.g., 0-10).
				The evaluator returns a normalized version of this score.
			2. Predicting a single score, but across `n_samples_judge` different judges.
				We then average the scores across multiple judges (if `n_samples_judge` > 1), and return the normalized average score.
			3. Predicting multiple quality scores across a variety of dimensions (e.g., relevance,
				coherence, etc.). We then aggregate initially within each dimension (e.g., average
				across multiple evaluators), and then aggregate across multiple dimensions, and
				return the normalized version of this aggregated score.

		Parameters:
			frontier: Nodes to evaluate.
			tree: Current tree structure.
			tot_parameters: Tree search configuration parameters.
			demos: Demos for evaluation (used for both PRM and ORM if specific demos not provided).
			demos_prm: Demos specifically for PRM evaluation (overrides `demos` for PRM).
			demos_orm: Demos specifically for ORM evaluation (overrides `demos` for ORM).

		Returns:
			List of evaluated nodes with assigned scores.

		Raises:
			AssertionError: If root node is in frontier.
		"""
		assert tree.root not in frontier, (
			"The root node should not be in the frontier since it doesn't include an output from the generator."
		)

		# Get states and validity flags using the helper function
		states, is_valid = self._get_states_and_validity(frontier)
		valid_states = [state for state, valid in zip(states, is_valid, strict=True) if valid]

		if valid_states:
			# TODO[P3]: Evaluator should also pass in vllm sampling params as kwargs.
			evaluation_results = self.evaluator(
				states=valid_states,
				n_samples_evaluator=tot_parameters.n_samples_judge,
				evaluator_temperature=tot_parameters.judge_temperature,
				evaluator_max_tokens=tot_parameters.judge_max_tokens,
				evaluator_top_p=tot_parameters.judge_top_p,
				evaluator_top_k=tot_parameters.judge_top_k,
				evaluator_min_p=tot_parameters.judge_min_p,
				evaluator_use_beam_search=tot_parameters.judge_use_beam_search,
				demos=demos,
				demos_prm=demos_prm,
				demos_orm=demos_orm,
			)
		else:
			logger.warning("No valid states to evaluate since all nodes failed parsing")
			evaluation_results = []

		# Assign scores to nodes
		# Assign scores to nodes
		eval_idx = 0
		for node, valid in zip(frontier, is_valid, strict=True):
			if valid:
				evaluation_result_list = evaluation_results[eval_idx]
				eval_idx += 1
				# Evaluator returns a list of results per state (usually length 1)
				# We take the first one as it contains the consolidated score
				evaluation_result = evaluation_result_list[0]
				node.score = evaluation_result.score
			else:
				# Assign 0 score to failed nodes and mark as pruned
				node.score = 0.0
				node.is_pruned = True
				error_detail = None
				error_type = None
				existing_steps = node.state.reasoning
				if existing_steps:
					last_step = existing_steps[-1]
					error = last_step.get("error", ExecutionError())
					if error.has_error():
						error_detail = error.error_message
						error_type = error.error_type
				if error_detail:
					if error_type == "parsing":
						node.reasoning = f"Failed to parse node {node.index}: {error_detail}"
					else:
						node.reasoning = f"Failed to evaluate node {node.index}: {error_detail}"
				else:
					if error_type == "parsing":
						node.reasoning = f"Failed to parse node {node.index}."
					else:
						node.reasoning = f"Failed to evaluate node {node.index}."

		return frontier

	def plan_actions(
		self,
		frontier: list[Node],
		tot_parameters: TreeOfThoughtsParameters,
		controller_demos: list[dict[str, Any]] | None = None,
		forced_controller_choices: dict[tuple[int, int], list[dict[str, Any]]] | None = None,
	) -> list[Node]:
		"""Plan actions for each node in the frontier by calling the controller.

		The controller generates n_samples_generation controller outputs for each parent node.
		These outputs are stored in the parent node's state.controller_outputs
		and will be used by the generator to create n_samples_generation children from
		each parent.

		Parameters:
			frontier: Nodes to plan actions for.
			tot_parameters: Tree search configuration parameters.
			controller_demos: Optional demos to guide controller decisions.
			forced_controller_choices: Optional dict mapping (depth, node_position) to forced actions.

		Returns:
			Frontier nodes with updated states (including controller_outputs) and steps.

		Raises:
			AssertionError: If nodes are not from the same layer.
		"""
		assert len({node.layer for node in frontier}) == 1, (
			"All nodes must be from the same layer"
		)

		# If the caller already forced a FINISH plan (e.g. TreeOfThoughts.forward() finalization),
		# don't override it by calling the controller again.
		if all(node.state.controller_outputs for node in frontier):
			all_forced_finish = all(
				all(not output.continue_reasoning for output in node.state.controller_outputs)
				for node in frontier
			)
			if all_forced_finish:
				return frontier

		# Don't call controller for last layer - set controller outputs to finish
		if frontier[0].layer == self.generator.max_reasoning_steps:
			n_final_candidates = (
				tot_parameters.n_final_responses_per_trajectory
				if tot_parameters.n_final_responses_per_trajectory is not None
				else tot_parameters.n_samples_generation
			)
			for node in frontier:
				controller_output = ControllerOutput(
					action="finish",
					action_arguments={},
					tool_descriptions="Action Name: finish",
					continue_reasoning=False,
					considerations="Max reasoning steps reached - generating final response",
					internal_reasoning="",
					prefix="",
					unique_action_response_count=n_final_candidates,
				)
				node.state.controller_outputs = [controller_output]
			return frontier

		# Determine temperature (controller override or default)
		controller_temp = (
			tot_parameters.controller_temperature
			if tot_parameters.controller_temperature is not None
			else tot_parameters.generator_temperature
		)

		controller_sampling_params: dict[str, Any] = {}
		controller_sampling_params["temperature"] = controller_temp
		controller_sampling_params["max_tokens"] = tot_parameters.controller_max_tokens
		controller_sampling_params["top_p"] = tot_parameters.controller_top_p
		controller_sampling_params["top_k"] = tot_parameters.controller_top_k
		controller_sampling_params["min_p"] = tot_parameters.controller_min_p
		if tot_parameters.controller_use_beam_search:
			controller_sampling_params["use_beam_search"] = True

		# Populate forced controller actions into states based on tree position
		if forced_controller_choices:
			current_layer = frontier[0].layer  # All frontier nodes are at same layer
			for i, node in enumerate(frontier):
				key = (current_layer, i)
				if key in forced_controller_choices:
					forced_choice_dicts = forced_controller_choices[key]
					node.state.forced_controller_outputs = [
						(
							choice_dict["action"],
							choice_dict["action_arguments"],
							choice_dict["considerations"],
						)
						for choice_dict in forced_choice_dicts
					]

		# Call controller to generate controller predictions for each parent node in the frontier
		# Controller returns list[list[ControllerPrediction]] where:
		#   - Outer list: one entry per parent node
		#   - Inner list: n_samples_generation controller predictions per parent
		# TODO[P2]: `plan_actions` applies forced choices based on the node's index in the pruned
		# frontier list, but we have no way of distinguishing whether these indices correspond to
		# trees that are pruned/non-pruned. We likely want to make forced controller choices more
		# generic (e.g., functions of a state/node object with access to the index) rather than
		# explicitly based on the index of a node in a given layer.
		controller_plans = self.controller(
			states=[node.state for node in frontier],
			n_samples_generation=tot_parameters.n_samples_generation,
			demos=controller_demos,
			**controller_sampling_params,
		)

		for node, plan in zip(frontier, controller_plans, strict=True):
			node.state.controller_outputs = [
				ControllerOutput(
					action=prediction.tool.name,
					action_arguments=prediction.chosen_values,
					tool_descriptions=prediction.tool.desc or str(prediction.tool),
					continue_reasoning=prediction.intervention.continue_reasoning,
					internal_reasoning=prediction.intervention.internal_reasoning,
					prefix=prediction.intervention.prefix,
					considerations=prediction.considerations,
					tool_execution_error=prediction.error or "",
					failed_tool=prediction.tool.name if prediction.error else "",
					unique_action_response_count=prediction.num_occurrences,
					score=prediction.score,
				)
				for prediction in plan
			]


		return frontier

	def select_nodes(
		self,
		judged_nodes: list[Node],
		tot_parameters: TreeOfThoughtsParameters,
		num_to_select: int | None = None,
		mark_non_selected_as_pruned: bool = True,
	) -> list[Node]:
		"""Select top nodes to continue based on selection strategy.

		This method is used for both intermediate thought selection and final
		output selection. The selection strategy (GREEDY or SAMPLE) is applied
		consistently across both use cases.

		Parameters:
			judged_nodes: Evaluated nodes to select from.
			tot_parameters: Tree search configuration parameters.
			num_to_select: Number of nodes to select. If None, uses tot_parameters.top_k
				(or top_k_first for layer 1 nodes if set).
			mark_non_selected_as_pruned: Whether to mark non-selected nodes as pruned.
				Should be True for intermediate beam search, False for final candidate selection.

		Returns:
			List of top nodes to explore (the new frontier or final selection).
		"""
		if num_to_select is not None:
			k = num_to_select
		elif (
			tot_parameters.top_k_first is not None
			and judged_nodes
			and judged_nodes[0].layer == 1
		):
			k = tot_parameters.top_k_first
		else:
			k = tot_parameters.top_k

		if tot_parameters.node_selection_strategy == NodeSelectionStrategy.GREEDY:
			# Select nodes greedily with random tie-breaking
			# Filter out already pruned nodes (e.g. failed parsing)
			candidates = [node for node in judged_nodes if not node.is_pruned]
			frontier = self._select_with_random_ties(candidates, k)
		# TODO[P0][Till]: Add MMR strategy for node selection
		else:  # NodeSelectionStrategy.SAMPLE
			# Select nodes with weighted sampling without replacement
			candidates = [node for node in judged_nodes if not node.is_pruned]
			values = np.array([child_node.score for child_node in candidates])
			total_score = np.sum(values)
			if total_score > 0:
				probabilities = values / total_score
				non_zero_indices = np.where(probabilities > 0)[0]
				sample_size = min(k, len(non_zero_indices))
				p = probabilities[non_zero_indices]
				p /= p.sum()
				frontier_indices = np.random.choice(
					non_zero_indices, size=sample_size, replace=False, p=p
				)
				frontier = [candidates[i] for i in frontier_indices]
			else:
				# If all scores are 0, just take the first k
				frontier = candidates[:k]

		# Sort by index to maintain consistent order
		frontier = sorted(frontier, key=lambda child_node: child_node.index)
		# Prune the nodes that were not selected (if enabled)
		if mark_non_selected_as_pruned:
			non_selected_nodes = [node for node in judged_nodes if node not in frontier]
			for node in non_selected_nodes:
				node.is_pruned = True
		return frontier
