"""Tree module for representing search trees with nodes and edges."""
# Standard imports
import json
import logging
import os
import time
from dataclasses import dataclass
from enum import Enum
from typing import Any

# Third-party imports
from pydantic import BaseModel, Field, model_validator

# Local imports
from misc_utils import stringify, stringify_without_metadata
from predict.controller.controller_constants import ControllerOutput
from tree.tree_constants import (
	NodeField,
	ReasoningState,
	TreeStructure,
)

logger = logging.getLogger(__name__)

# Input maps input fields to their values.
Input = dict[str, Any]
# Reasoning is a list of step dictionaries (i.e., one dictionary per step) created by the generator
Reasoning = list[dict[str, Any]]
# Output maps from the name of the output field to the final response created by the generator for
# that field.
Output = dict[str, Any]
# Action maps `action_name` to a string and `action_arguments`to an inner dictionary that maps
# from the name of an argument to its description (purpose and possible values).
Action = dict[str, dict[str, Any]]


class TreeEncoder(json.JSONEncoder):
	"""JSON encoder that handles Enum serialization."""

	def default(self, o: Any) -> Any:
		"""Convert Enum objects to strings for JSON serialization.

		Args:
			o: Object to encode. If it's an Enum, convert to string.

		Returns:
			String representation of Enum, or calls parent default method.
		"""
		if isinstance(o, Enum):
			return str(o)
		return super().default(o)


@dataclass
class JudgeEvaluation:
	"""
	Represents a single judge's evaluation with both raw and normalized scores.

	Attributes:
	    raw_scores: Dictionary mapping dimension names to raw scores (e.g., 1-7 Likert scale values).
	    normalized_scores: Dictionary mapping dimension names to normalized scores in [0, 1] range.
	"""

	raw_scores: dict[str, float]
	normalized_scores: dict[str, float]


@dataclass
class EvaluationResult:
	"""
	Complete evaluation result for a state, containing aggregated and individual judge evaluations.

	Attributes:
	    score: Total normalized score [0, 1], averaged across all dimensions and judges.
	    judge_evaluations: List of individual judge evaluations with raw and normalized scores.
	        Each JudgeEvaluation contains raw_scores, normalized_scores, and feedback for one judge.
	        Aggregated subscores and feedback lists can be computed from this field if needed.
	"""

	score: float
	judge_evaluations: list[JudgeEvaluation]

class State(BaseModel):
	"""
	A representation of reasoning over a problem.
	A state consists of three components:
	    1. An input (`x`) that represents the problem to be solved. In practice, this is a dictionary mapping input fields to
	        their values.
	    2. A set of intermediate predictions (`z_1, ..., z_i`) that represent the reasoning steps generated so far.
	        Intermediate predictions are generated by the generator and are used to generate the final response.
	    3. A final prediction (`y`) that represents the final response generated by the generator. The final prediction is
	        generated based on the input and the intermediate predictions.
	"""

	input: Input = Field(
		...,
		description="The input problem to be solved. This is a dictionary mapping input fields to their values.",
		alias=ReasoningState.INPUT,
	)
	controller_output_trajectory: list[ControllerOutput] = Field(
		default_factory=list,
		description="""
Historical trajectory of controller outputs from root to current node.
Each ControllerOutput contains both the decision (action, arguments, considerations)
and execution result (continue_reasoning, prefix, internal_reasoning).
Accumulates as we traverse deeper into the tree and is used for
visualization, debugging, and path analysis.
""".strip(),
		alias="controller_output_trajectory",
	)
	controller_outputs: list[ControllerOutput] = Field(
		default_factory=list,
		description="""
Current controller outputs for expanding this state. These are the
deduplicated outputs from the most recent controller call.
Each contains both the decision and the tool execution result.
Gets cleared when creating child nodes.
""".strip(),
		alias="controller_outputs",
	)
	forced_controller_outputs: list[tuple[str, dict[str, Any], str]] | None = Field(
		default=None,
		description="""Optional pre-specified controller choices for testing/debugging.
When set, the controller will use these instead of calling the LM.
Each tuple should contain (action_name, action_arguments, considerations).
The intervention fields (continue_reasoning, prefix, internal_reasoning, etc.) are automatically
populated by executing the tool with these choices.""",
	)
	reasoning: Reasoning = Field(
		default_factory=list,
		description="""
List of intermediate reasoning steps (step dictionaries).
This list is stored under the top-level key `ReasoningState.REASONING` in serialized state.
""".strip(),
		alias=ReasoningState.REASONING,
	)
	feedback: list[str] = Field(
		default_factory=list,
		description="""
A list containing the feedback for each reasoning step produced by the generator so far.
Each feedback item corresponds to a string (essentially advice) provided by the evaluator for a reasoning step.
Feedback is meant to guide the generator towards producing high-quality subsequent reasoning steps.
""".strip(),
		alias=ReasoningState.FEEDBACK,
	)
	output: Output = Field(
		default_factory=dict,
		description="""
An answer to the task/problem. This is the final prediction generated by the generator.
The output is a dictionary mapping output fields to their values.
""".strip(),
		alias=ReasoningState.OUTPUT,
	)

	@model_validator(mode="after")
	def _validate_reasoning_steps(self) -> "State":
		if not isinstance(self.reasoning, list):
			raise TypeError("State.reasoning must be a list of step dictionaries.")
		for step in self.reasoning:
			if not isinstance(step, dict):
				raise TypeError(
					f"State.reasoning must contain step dictionaries, got {type(step)}."
				)
		return self

	def model_output_so_far(self) -> str:
		"""
		Render the model's output so far for this trajectory.

		This reconstructs the exact assistant content representing the completed reasoning
		steps (`<thinking>` with `<step>` blocks) and, if present, the final output
		(`</thinking>` followed by `<answer>`).

		Returns:
			The assistant message content string corresponding to this state's reasoning/output.
		"""
		if not self.reasoning and not self.output:
			return ""

		lines: list[str] = ["<thinking>"]

		for step_index, step in enumerate(self.reasoning):
			lines.append("<step>")

			if step_index < len(self.controller_output_trajectory):
				internal_reasoning = self.controller_output_trajectory[step_index].internal_reasoning
				internal_reasoning = str(internal_reasoning).strip()
				if internal_reasoning and "internal_reasoning" not in step:
					lines.append("## internal_reasoning")
					lines.append(internal_reasoning)

			for field_name, value in step.items():
				# Metadata keys should not be injected back into the model context.
				if field_name == "error":
					continue
				lines.append(f"## {field_name}")
				lines.append(str(value).strip())

			lines.append("</step>")

		if not self.output:
			# Intermediate node: do not close </thinking> so generation can continue.
			return "\n".join(lines)

		lines.append("</thinking>")
		lines.append("<answer>")

		for field_name, value in self.output.items():
			# Metadata keys should not be injected back into the model context.
			if field_name == "error":
				continue
			lines.append(f"## {field_name}")
			if isinstance(value, str):
				lines.append(value.strip())
			else:
				lines.append(stringify(value).strip())

		lines.append("</answer>")
		return "\n".join(lines)


class Node(BaseModel):
	"""
	A node within a search tree, which represents a reasoning step towards completing a task.

	The default search algorithm in which a node is used is Beam Search (as in the original Tree of Thoughts paper by
	Yao et al., 2023). A node contains a `state` (reasoning for tackling the task), a `score` that is assigned to
	the state by an evaluator, and `reasoning` for why the evaluator assigned the score. The node also contains an `index`
	that uniquely identifies it in the tree, a `layer` that represents the depth of the node in the tree, and a `parent_id`
	that points to the index of the parent node in the tree. The node can have multiple children, which are stored in the
	`children_ids` field.

	While a `State` represents the input and reasoning steps generated so far, a `Node` wraps the state and adds additional
	metadata which is used in the search tree. The tree operates agnostically with respect to the state and only uses the
	metadata in the node to traverse the tree and generate an answer for the task.
	"""

	state: State = Field(
		...,
		description="""
A representation of both the problem input (`x`) and the reasoning steps (`z_1, ..., z_i`) that have been generated so far.
If a state contains `n` reasoning steps (`z_1, ..., z_n`), then the child node will contain a final response `y` that
is a "final answer" for the task (`x`). After generating the final response, `y` is included in the state of the child node.
""".strip(),
	)
	score:  float | None = Field(
		default=None,
		description="""
The reasoning behind the score of this node. The reasoning is produced by an evaluation model (or an ensemble of them)
alongside the score they assign to the node. A higher score indicates that the node is more promising in terms of generating
a high-quality response. The score is a float between 0 and 1, where 1 indicates high-quality and 0 indicates low quality.
""".strip(),
		ge=0,
		le=1,
	)
	reasoning:  str | None = Field(
		default=None,
		description="""
The reasoning behind the score assigned to the node (generated by LLM judges alongside the scores they provide).
""".strip(),
	)
	index: int = Field(
		...,
		description="The (positive) index of the node in the tree. A unique identifier for the node.",
		ge=0,
	)
	layer: int = Field(
		...,
		description="""
The layer of the node in the tree. Layers are ordered from top-to-bottom, where the root node is at layer 0,
and the leaf nodes are at the maximum layer. The layer of a node is the number of edges in the shortest path from the root
to the node. Nodes in deeper layers are presumably closer to solving the problem or generating the response.
""".strip(),
		ge=0,
	)
	is_pruned: bool = Field(
		default=False,
		description="""
Whether the node has been pruned from the tree. Pruning occurs when there are more children nodes than a pre-determined
threshold (`top_k`). If `is_pruned` is True, then the node is not expanded further, as it was deemed less promising than
other nodes in the same layer (i.e., it was not among the top `top_k` scoring nodes in the layer). If `is_pruned` is False,
then the node is expanded further, and its children are added to the tree.
""".strip(),
	)
	parent_id: int | None = Field(
		default=None,
		description="""
The index of the parent node of this node. The most recent reasoning step in the state of this node was generated by the parent
node. The layer of the parent node is one less than the layer of this node.
""".strip(),
		ge=0,
	)
	children_ids: list[int] | None = Field(
		default_factory=list,
		description="""
The indices of the children of this node. The edges to each child correspond with possible actions (intermediate
thoughts/reasoning steps or responses) that the language model can take from the current state. The children nodes
represent the possible states that can be reached from the current state via those actions.
""".strip(),
	)
	metrics: dict[str, float] | None = Field(
		default=None,
		description="""
Metrics for thoughts/responses across a collection of evaluation dimensions.
Language model evaluators predict these scores, and they are used to compute an "overall score" for a candidate child node.
Feedback consists of non-deteministic metrics such as `fluency`, `relevance`, `coherence`, `consistency`, etc...
""".strip(),
	)

	def __lt__(self, other: "Node") -> bool:
		"""Compare nodes by their scores for sorting.

		Args:
			other: Another Node to compare against.

		Returns:
			True if this node's score is less than the other node's score,
			False otherwise. None scores are treated as less than any number.
		"""
		if self.score is None and other.score is None:
			return False
		elif self.score is None:
			return True
		elif other.score is None:
			return False
		else:
			return self.score < other.score


class ReasoningChain(BaseModel):
	"""A chain of reasoning nodes leading to a final response.

	Each reasoning chain represents the sequence of nodes (containing reasoning steps) that were
	taken to arrive at a final response.
	The chain includes all reasoning steps from the root to the final node.
	"""

	nodes: list[Node] = Field(
		...,
		description="List of nodes in the reasoning chain from root to final response.",
	)

	@classmethod
	def from_node_path(cls, nodes: list[Node]) -> "ReasoningChain":
		"""Create a ReasoningChain from a list of nodes."""
		return cls(nodes=nodes)

	def controller_trajectory(self) -> list[tuple[str, dict[str, Any]]]:
		"""Controller tool names and arguments per reasoning step.

		Walks the root-to-leaf path and collects the controller output that led to
		each node (excluding the root). Each node's state.controller_output_trajectory
		holds the outputs along the path to that node.

		Returns:
			List of (tool_name, action_arguments) for each step along the path.
		"""
		result: list[tuple[str, dict[str, Any]]] = []
		for node in self.nodes[1:]:  # skip root
			trajectory = node.state.controller_output_trajectory
			if trajectory:
				co = trajectory[-1]
				result.append((co.action, dict(co.action_arguments)))
		return result

	def __str__(self) -> str:
		"""Return a string representation of the reasoning chain.

		Shows the full reasoning chain with layer information and reasoning step content.
		"""
		lines = []
		for i, node in enumerate(self.nodes):
			layer_info = f"[Layer {node.layer}]"
			if node.state.output:
				step_str = (
					f"Final Response Content:\n\t{stringify_without_metadata(node.state.output)}"
				)
			elif i == 0:
				step_str = f"Root node (initial state):\n\t{stringify(node.state.input)}"
			else:
				# Get reasoning step content for intermediate nodes
				reasoning_steps = node.state.reasoning
				if reasoning_steps:
					# Get the most recent reasoning step
					step_data = reasoning_steps[-1]
					step_str = f"Reasoning Content:\n\t{stringify_without_metadata(step_data)}"
				else:
					raise ValueError(
						f"Node {node.index} has no reasoning steps or output and is not a root node:"
						f"\nNode:\n{node}"
					)
			lines.append(f"\t{i + 1}. {layer_info} {step_str}")
		return "\n".join(lines)


class Edge(BaseModel):
	"""
	An edge in a search tree that connects two nodes and represents a reasoning step.

	If the generator produced a reasoning step at node `i`, then the edge from that node to its child (in layer `i+1`)
	will contain the content of the reasoning step (e.g., a claim when generating an argument, or an intermediate
	function or class when generating code). The granularity of the reasoning step depends on both the task and the reasoning
	type (`iterative_drafting` vs. `plan_and_execute`, vs. `additive_reasoning` vs. `devils_advocate`).
	"""

	reasoning_step: str = Field(
		..., description="A reasoning step or final response created by the generator."
	)


class Tree(BaseModel):
	"""
	A search tree for a task that requires additive reasoning to solve.

	The tree is constructed using a search algorithm (e.g., Beam Search and MCTS), where each node represents a reasoning step
	towards completing the task.
	The tree contains nodes, edges, and layers, where each layer represents a level of reasoning depth.
	The tree can be visualized as a directed graph, where nodes are connected by edges (that represent the reasoning steps taken
	to reach the next node).

	The input problem (`x`) is passed to the root node, and the tree is expanded by adding reasoning steps (`z`) to the
	state of each node. The final response (`y`) is generated based on the reasoning steps that precede it.
	"""

	root: Node = Field(
		...,
		description="The root node of the tree. This node contains the initial state of the task.",
	)
	nodes: dict[int, Node] = Field(
		default_factory=dict,
		description="A dictionary of nodes in the tree, where the key is the index of the node and the value is the node itself.",
	)
	edges: dict[int, dict[int, Edge]] = Field(
		default_factory=dict,
		description="A dictionary of edges in the tree, where the key is the index of the source node and the value is a dictionary of target nodes and their corresponding edges.",
	)
	layers: list[list[Node]] = Field(
		default_factory=list,
		description="A list of layers in the tree, where each layer contains nodes at the same depth in the tree.",
	)

	@staticmethod
	def _assert_node_is_valid(node: Node) -> Node:
		"""Assert that the node is valid."""
		assert isinstance(node, Node), (
			f"Node should be of type `Node`, but got {type(node)}."
		)
		assert node.state.input, (
			f"Node {node.index} should contain an input.\nNode:\n{node}"
		)
		# Check root node constraints: if parent_id is None, it must be a root node
		if node.parent_id is None or node.layer == 0:
			assert node.layer == 0, (
				f"Root node should be in layer 0, but got {node.layer}.\nRoot:\n{node}"
			)
			assert node.index == 0, (
				f"Root node should have index 0, but got {node.index}.\nRoot:\n{node}"
			)
			assert not node.state.reasoning, (
				f"Root node should not contain reasoning steps.\nRoot:\n{node}"
			)
			assert not node.state.output, (
				f"Root node should not contain a final response.\nRoot:\n{node}"
			)
			assert node.index == 0, (
				f"Root node should have index 0, but got {node.index}.\nRoot:\n{node}"
			)
			assert node.parent_id is None, (
				f"Root node should not have a parent.\nRoot:\n{node}"
			)
			assert not node.state.reasoning, (
				f"Root node should not contain reasoning steps.\nRoot:\n{node}"
			)
			assert not node.state.output, (
				f"Root node should not contain a final response.\nRoot:\n{node}"
			)
		elif bool(node.state.reasoning) and not bool(node.state.output):
			# Intermediate node (subsequent or final step)
			assert node.parent_id is not None, (
				f"Node {node.index} should have a parent.\nProblematic node:\n{node}"
			)
		elif bool(node.state.output):
			# Done node (has final output)
			assert node.parent_id is not None, (
				f"Node {node.index} should have a parent.\nProblematic node:\n{node}"
			)
		return node

	@staticmethod
	def _assert_nodes_are_valid(nodes: dict[int, Node]) -> dict[int, Node]:
		"""Assert that the nodes are valid."""
		assert isinstance(nodes, dict), (
			f"Expected nodes to be a dictionary, but got {nodes}."
		)
		assert len(nodes) > 0, "nodes must not be empty"
		assert all(isinstance(key, int) for key in nodes.keys()), (
			"Expected nodes to use integer keys."
		)
		assert all(isinstance(node, Node) for node in nodes.values()), (
			"Expected all node values to be Node instances."
		)
		return nodes

	@staticmethod
	def _assert_edges_are_valid(
		edges: dict[int, dict[int, Edge]],
	) -> dict[int, dict[int, Edge]]:
		"""Assert that the edges are valid."""
		assert isinstance(edges, dict), (
			f"Expected edges to be a dictionary, but got {edges}."
		)
		if len(edges) > 0:
			assert isinstance(list(edges.keys())[0], int), (
				f"Expected edges to be a dictionary with integer keys, but got {list(edges.keys())[0]}."
			)
			assert isinstance(edges[0], dict), (
				f"Expected edges to be a nested dictionary, but got {edges[0]}."
			)
			assert isinstance(list(edges[0].keys())[0], int), (
				f"Expected edges to be a nested dictionary with integer keys, but got {list(edges[0].keys())[0]}."
			)
			if len(edges[0]) > 0:
				assert isinstance(list(edges[0].values())[0], Edge), (
					f"Expected edges to be a nested dictionary with Edge values, but got {edges[0][0]}."
				)
		return edges

	@model_validator(mode="before")
	@classmethod
	def initialize_tree(cls, values: dict[str, Any]) -> dict[str, Any]:
		"""Initialize a tree of thoughts from various input formats.

		This validator handles multiple initialization cases:
		1. State-only: Create a new tree from an initial state dictionary.
		2. Root-only: Initialize from a single root node.
		3. Root + Nodes + Edges: Reconstruct a tree with all components specified.
		4. Nodes-only: Reconstruct a tree from nodes dictionary (dynamically constructs edges).

		Args:
			cls: The class reference (automatically provided by @classmethod).
			values: Dictionary containing one of:
				- 'state': Dictionary mapping input field names to values.
					This becomes the `State` within the root node of the tree.
				- 'root': Root Node object (for root-only initialization).
				- 'nodes': Dictionary mapping node indices to Node objects.
				- 'edges': Optional nested dictionary of Edge objects between nodes.

		Returns:
			Dictionary containing validated tree components:
				- 'root': Root Node object.
				- 'nodes': Dictionary of all nodes.
				- 'edges': Dictionary of all edges.
				- 'layers': List of lists of nodes by layer.

		Raises:
			ValueError: If no valid initialization case is provided.
			AssertionError: If nodes or edges fail validation.
		"""
		if NodeField.STATE in values and values[NodeField.STATE]:
			return cls._init_from_state(values[NodeField.STATE])

		if TreeStructure.ROOT in values and values[TreeStructure.ROOT] and not values.get(TreeStructure.NODES) and not values.get(TreeStructure.EDGES):
			return cls._init_from_root(values[TreeStructure.ROOT])

		if all(k in values for k in [TreeStructure.ROOT, TreeStructure.NODES, TreeStructure.EDGES]):
			return cls._init_from_nodes(
				nodes=values[TreeStructure.NODES],
				edges=values[TreeStructure.EDGES],
			)

		if TreeStructure.NODES in values and values[TreeStructure.NODES]:
			return cls._init_from_nodes(
				nodes=values[TreeStructure.NODES],
				edges=values.get(TreeStructure.EDGES),
			)

		raise ValueError(
			"Either an initial state, a root node, nodes collection, "
			f"or root/nodes/edges must be provided.\nInstead got: {values}."
		)

	@classmethod
	def _init_from_state(cls, state: dict[str, Any]) -> dict[str, Any]:
		"""Initialize a tree from a state dictionary.

		Creates a root node with the provided state and returns a tree structure
		with a single root node at layer 0.

		Args:
			state: Dictionary mapping input field names to their values.

		Returns:
			Dictionary containing TreeStructure.ROOT, TreeStructure.NODES, TreeStructure.EDGES, and TreeStructure.LAYERS keys for tree
			initialization.
		"""
		root_state = State(input=state)
		root = Node(index=0, layer=0, state=root_state)
		return {
			TreeStructure.ROOT: root,
			TreeStructure.NODES: {root.index: root},
			TreeStructure.EDGES: {},
			TreeStructure.LAYERS: [[root]],
		}

	@classmethod
	def _init_from_root(cls, root: Node) -> dict[str, Any]:
		"""Initialize a tree from a single root node.

		Validates the root node and returns a tree structure containing only
		the root node.

		Args:
			root: Root node to initialize the tree from. Must be valid (layer 0,
				index 0, no parent, no reasoning, no output).

		Returns:
			Dictionary containing TreeStructure.ROOT, TreeStructure.NODES, TreeStructure.EDGES, and TreeStructure.LAYERS keys for tree
			initialization.

		Raises:
			AssertionError: If the root node is invalid.
		"""
		cls._assert_node_is_valid(root)
		nodes = {root.index: root}
		return {
			TreeStructure.ROOT: root,
			TreeStructure.NODES: nodes,
			TreeStructure.EDGES: {},
			TreeStructure.LAYERS: [[root]],
		}

	@classmethod
	def _init_from_nodes(
		cls,
		nodes: dict[int, Node],
		edges: dict[int, dict[int, Edge]] | None = None,
	) -> dict[str, Any]:
		"""Initialize a tree from a dictionary of nodes and optional edges.

		Validates nodes and edges, identifies the root node (must be exactly one at layer 0),
		and organizes nodes into layers. Also validates that all non-root nodes have valid
		parent_id references.

		Args:
			nodes: Dictionary mapping node indices to Node objects. Must contain exactly one root
				node at layer 0. All non-root nodes must have parent_id set to an existing node
				index.
			edges: Optional dictionary mapping source node indices to dictionaries
				of target node indices and their corresponding Edge objects.

		Returns:
			Dictionary containing TreeStructure.ROOT, TreeStructure.NODES, TreeStructure.EDGES,
			and TreeStructure.LAYERS keys for tree initialization.

		Raises:
			AssertionError: If nodes are invalid, if there is not exactly one root node, if edges
				are invalid, or if any non-root node has a missing or invalid parent_id.
		"""
		cls._assert_nodes_are_valid(nodes)
		nodes_copy = dict(nodes.items())
		root_candidates = [node for node in nodes_copy.values() if node.layer == 0]
		assert len(root_candidates) == 1, (
			f"Expected exactly one root node at layer 0, got {len(root_candidates)}."
		)
		root = root_candidates[0]

		# Validate that all non-root nodes have valid parent_id references
		for node in nodes_copy.values():
			if node.layer > 0:
				assert node.parent_id is not None, (
					f"Node {node.index} at layer {node.layer} must have a parent_id. "
					f"Only the root node (layer 0) can have parent_id=None."
				)
				assert node.parent_id in nodes_copy, (
					f"Node {node.index} has parent_id={node.parent_id}, but no node with "
					f"that index exists in the provided nodes dictionary."
				)

		edges = edges or {}
		cls._assert_edges_are_valid(edges)
		if root.index not in nodes_copy:
			nodes_copy[root.index] = root
		max_layer = max(node.layer for node in nodes_copy.values())
		layers = [
			[node for node in nodes_copy.values() if node.layer == layer]
			for layer in range(max_layer + 1)
		]
		return {
			TreeStructure.ROOT: root,
			TreeStructure.NODES: nodes_copy,
			TreeStructure.EDGES: edges,
			TreeStructure.LAYERS: layers,
		}

	def add_layer(self, layer: list[Node]) -> None:
		"""
		Adds a layer to the tree.

		Parameters:
		    layer (List[Node]): The layer to add to the tree.
		"""
		self.layers.append(layer)

	def add_edge(self, source_index: int, target_index: int, edge: Edge) -> None:
		"""
		Add an edge to the tree from the source node to the target node.

		Parameters:
		    source_index (int): The index of the source node.
		    target_index (int): The index of the target node.
		    edge (Edge): The edge to add. Contains the reasoning step or response generated by the generator in the source node.
		"""
		if source_index not in self.edges:
			self.edges[source_index] = {}
		self.edges[source_index][target_index] = edge

	@staticmethod
	def _assert_output_is_valid(
		output: Reasoning | Output,
	) -> Reasoning | Output:
		"""
		Assert that the output is valid.

		Validity checks include:
		    - The output is a dictionary.
		    - The output is not empty.
		    - The keys of the output are strings.
		"""
		assert isinstance(output, dict), (
			f"Expected output to be a dictionary, but got {output}."
		)
		assert len(output) > 0, "Output must not be empty."
		assert all(isinstance(k, str) for k in output.keys()), (
			f"Expected output to be a dictionary with string keys, but got keys: {list(output.keys())}"
		)

		return output

	@staticmethod
	def _assert_parent_node_is_valid(parent_node: Node) -> Node:
		"""
		Assert that the parent node is valid.

		Validity checks include:
		    - The parent node is of type `Node`.
		    - The parent node does not have a final output (can still be expanded or is pruned from the tree).
		"""
		assert isinstance(parent_node, Node), (
			f"Expected parent node to be of type `Node`, but got {type(parent_node)}."
		)
		assert not parent_node.state.output, (
			f"Expected parent node (#{parent_node.index}) to not have a final output "
			f"(can still be expanded), but it has output: {parent_node.state.output}."
		)
		return parent_node

	def create_child_node(
		self,
		parent_node: Node,
		output: Reasoning | Output,
		controller_output: ControllerOutput,
	) -> Node:
		"""
		Creates a child for a specified parent node, and adjusts the tree structure accordingly.

		To create a child node, we concatenate the new reasoning step to the existing reasoning
		steps in the state of the parent node. If the step is the final step, we add the final
		response to the state of the child node instead.

		NOTE: The side effect of this method is to modify the parent node (include a new child
		among its list of children), add a node to the tree's dictionary of nodes, and add an edge
		to the tree's dictionary edges. The new child node's parent is set to the provided parent
		node.

		Parameters:
			parent_node (Node): The parent node to create a child node from. The new node will be
				added as a child of the parent node. The parent node will also be added as a
				parent of the child node. There will be an edge connecting the parent node to the
				child node.
			output (Reasoning | Output): A dictionary containing the output from the generator.
				This dictionary includes either an intermediate reasoning step or a final response
				for the	inputted task. An intermediate reasoning step is the value associated with
				the reasoning field key, while the final response (which is a dictionary
				that includes the fields specified in `output_field_names`) is the value associated
				with the `output` key.
			controller_output (ControllerOutput): The controller output that led to this child's
				generation. This output will be added to the child's controller_output_trajectory.

		Returns:
			Node: The newly created child node.
		"""
		# Parent node should not have final output (can still be expanded)
		assert not parent_node.state.output, (
			f"Expected parent node (#{parent_node.index}) to not have a final output "
			f"(can still be expanded), but it has output: {parent_node.state.output}."
		)
		child_state = parent_node.state.model_copy(deep=True)
		# Clear current outputs - child will get its own when controller is called on it
		child_state.controller_outputs = []
		# Add the output that led to this child's creation to the trajectory
		child_state.controller_output_trajectory.append(controller_output)

		# Ensure existing reasoning steps are initialized
		# This ensures consistency even for first steps or final outputs
		existing_reasoning_steps: list[dict[str, Any]] = list(child_state.reasoning)

		if controller_output.continue_reasoning:
			# This is a reasoning step (intermediate step)
			# Append the entire output dict (contains all reasoning fields)
			existing_reasoning_steps.append(output)
			child_state.reasoning = existing_reasoning_steps
		else:
			# Controller chose to finish - this is a final output
			child_state.output = output
			child_state.reasoning = existing_reasoning_steps
		child_node = Node(
			index=len(self.nodes), state=child_state, layer=parent_node.layer + 1
		)

		if not output and (controller_output.tool_execution_error or controller_output.failed_tool):
			child_node.is_pruned = True
			error_msg = "Unknown error: No reasoning or output produced."
			if controller_output.tool_execution_error:
				error_msg = f"Error: {controller_output.tool_execution_error}"
			elif controller_output.failed_tool:
				error_msg = f"Error: Tool '{controller_output.failed_tool}' failed to generate valid output."
			formatted_output = error_msg
		else:
			formatted_output = stringify_without_metadata(output)

		# Child node state is determined by controller_output.continue_reasoning:
		# - If continue_reasoning=False, child has output (done)
		# - If continue_reasoning=True, child has reasoning (intermediate)
		if parent_node.children_ids is None:
			parent_node.children_ids = []
		parent_node.children_ids.append(child_node.index)
		child_node.parent_id = parent_node.index
		self.nodes[child_node.index] = child_node
		self.add_edge(
			source_index=parent_node.index,
			target_index=child_node.index,
			edge=Edge(reasoning_step=formatted_output),
		)
		return child_node

	def tree_to_json(self) -> dict[str, Any]:
		"""
		Generates a JSON representation of the search tree as a Python dictionary.

		Returns:
			Dict[str, Any]: The JSON representation of the search tree as a Python dictionary.
		"""
		root = self.root.model_dump()
		nodes = {
			node_index: node_value.model_dump()
			for node_index, node_value in self.nodes.items()
		}
		edges = {
			source: {target: edge.model_dump() for target, edge in targets.items()}
			for source, targets in self.edges.items()
		}
		tree_data = {
			str(TreeStructure.ROOT): root,
			str(TreeStructure.NODES): nodes,
			str(TreeStructure.EDGES): edges,
		}
		return tree_data

	@classmethod
	def from_nodes(cls, nodes: list[Node]) -> "Tree":
		"""
		Create a Tree instance from pre-constructed nodes.

		The method links parent-child relationships, constructs edges using available
		reasoning/output data, and leaves the original node objects untouched.

		Args:
			nodes: List of nodes where exactly one node is the root (layer 0).

		Returns:
			Tree assembled from the provided nodes.
		"""
		assert nodes, "nodes must not be empty"
		root_candidates = [node for node in nodes if node.layer == 0]
		assert len(root_candidates) == 1, (
			f"Expected exactly one root node at layer 0, got {len(root_candidates)}."
		)
		root_index = root_candidates[0].index

		# Work on deep copies to avoid mutating provided nodes
		nodes_by_index = {node.index: node.model_copy(deep=True) for node in nodes}
		root_node = nodes_by_index[root_index]
		tree = cls(root=root_node, nodes={root_node.index: root_node}, edges={})

		for node in sorted(nodes_by_index.values(), key=lambda item: item.index):
			if node.index == root_node.index:
				continue
			assert node.parent_id is not None, \
				f"Node {node.index} must have a parent_id when reconstructing tree."
			parent = nodes_by_index.get(node.parent_id)
			assert parent is not None, \
				f"Parent with index {node.parent_id} for node {node.index} not found."
			tree.nodes[node.index] = node
			if parent.children_ids is None:
				parent.children_ids = []
			if node.index not in parent.children_ids:
				parent.children_ids.append(node.index)

			# Determine the content of the edge (reasoning/output that led to this node)
			existing_reasoning = node.state.reasoning
			if existing_reasoning:
				edge_reasoning_str = stringify_without_metadata(existing_reasoning[-1])
			elif node.state.output:
				edge_reasoning_str = stringify_without_metadata(node.state.output)
			else:
				raise ValueError(f"Node {node.index} has no reasoning or output and is not a root node: {node}")

			tree.add_edge(
				source_index=node.parent_id,
				target_index=node.index,
				edge=Edge(reasoning_step=edge_reasoning_str),
			)

		return tree

	def get_path_to_node(self, target_node: Node) -> list[Node]:
		"""Get the path from root to a target node in the tree.

		Returns a list of nodes representing the reasoning chain from root to target.

		Parameters:
			target_node: The target node to trace the path to.

		Returns:
			List of nodes from root to target (including root).
		"""
		path = []
		current: Node | None = target_node

		# Trace back from target to root
		while current is not None:
			path.append(current)
			if current.parent_id is None:
				break
			current = self.nodes.get(current.parent_id)

		# Reverse to get path from root to target
		path.reverse()
		return path

	@staticmethod
	def save_json_to_file(
		tree_json: dict[str, Any],
		directory_path: str | None = None,
		file_name: str | None = None,
		include_date_time: bool = True,
	) -> None:
		"""Save a JSON object representing a tree to a file.

		Creates the directory if it doesn't exist and writes the JSON to a file.
		If no file name is provided, generates one with optional timestamp.
		If a file name is provided and include_date_time is True, appends timestamp
		before the file extension.

		Args:
			tree_json: Dictionary containing tree data to save as JSON.
			directory_path: Optional path to directory where file should be saved.
				Defaults to current directory.
			file_name: Optional name for the JSON file. If not provided, generates
				a name with optional timestamp. If provided and include_date_time is True,
				timestamp is appended before the file extension.
			include_date_time: Whether to include timestamp in file name.
				Defaults to True.
		"""
		if directory_path is None:
			directory_path = "./"
		if not os.path.exists(directory_path):
			os.makedirs(directory_path, exist_ok=True)

		if file_name is None:
			file_name = (
				f"additive_reasoning_tree_{time.strftime('%Y-%m-%d_%H-%M-%S')}.json"
				if include_date_time
				else "additive_reasoning_tree.json"
			)
		elif include_date_time:
			# Append timestamp before file extension
			timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")
			if file_name.endswith(".json"):
				file_name = f"{file_name[:-(len('.json'))]}_{timestamp}.json"
			else:
				file_name = f"{file_name}_{timestamp}.json"
		json_path = os.path.join(directory_path, file_name)
		json_string = json.dumps(tree_json, indent=4, cls=TreeEncoder)
		with open(json_path, "w") as file:
			logger.info(f"Saving tree to {json_path}")
			file.write(json_string)

	def save_to_file(
		self,
		directory_path: str | None = None,
		file_name: str | None = None,
		include_date_time: bool = True,
	) -> dict[str, Any]:
		"""
		Save the search tree to a JSON file and return the JSON object.

		Parameters:
		    directory_path (str): The path to the directory where the file should be saved.
		    file_name (str): The name of the file to save the tree to.
		    include_date_time (bool): Whether to include the current date and time in the file name.

		Returns:
		    Dict[str, Any]: The JSON representation of the search tree as a Python dictionary.
		"""
		tree_json = self.tree_to_json()
		self.save_json_to_file(
			tree_json=tree_json,
			directory_path=directory_path,
			file_name=file_name,
			include_date_time=include_date_time,
		)
		return tree_json
